var searchData=
[
  ['ratelimitexceededexception',['RateLimitExceededException',['../d1/d25/classdatasift_1_1RateLimitExceededException.html',1,'datasift']]],
  ['readasbytestestobject',['ReadAsBytesTestObject',['../d1/d16/classNewtonsoft_1_1Json_1_1Tests_1_1Linq_1_1JTokenReaderTest_1_1ReadAsBytesTestObject.html',1,'Newtonsoft::Json::Tests::Linq::JTokenReaderTest']]],
  ['reflectiondelegatefactory',['ReflectionDelegateFactory',['../db/d73/classNewtonsoft_1_1Json_1_1Utilities_1_1ReflectionDelegateFactory.html',1,'Newtonsoft::Json::Utilities']]],
  ['reflectionutilstests',['ReflectionUtilsTests',['../d4/d3b/classNewtonsoft_1_1Json_1_1Tests_1_1Utilities_1_1ReflectionUtilsTests.html',1,'Newtonsoft::Json::Tests::Utilities']]],
  ['reflectionvalueprovider',['ReflectionValueProvider',['../d3/dbb/classNewtonsoft_1_1Json_1_1Serialization_1_1ReflectionValueProvider.html',1,'Newtonsoft::Json::Serialization']]],
  ['regexconverter',['RegexConverter',['../d0/dc0/classNewtonsoft_1_1Json_1_1Converters_1_1RegexConverter.html',1,'Newtonsoft::Json::Converters']]],
  ['regexconvertertests',['RegexConverterTests',['../d9/db0/classNewtonsoft_1_1Json_1_1Tests_1_1Converters_1_1RegexConverterTests.html',1,'Newtonsoft::Json::Tests::Converters']]],
  ['regextestclass',['RegexTestClass',['../dd/da4/classNewtonsoft_1_1Json_1_1Tests_1_1Converters_1_1RegexConverterTests_1_1RegexTestClass.html',1,'Newtonsoft::Json::Tests::Converters::RegexConverterTests']]],
  ['requestonly',['RequestOnly',['../d7/d6e/classNewtonsoft_1_1Json_1_1Tests_1_1TestObjects_1_1RequestOnly.html',1,'Newtonsoft::Json::Tests::TestObjects']]],
  ['requiredmembersclass',['RequiredMembersClass',['../d9/d3f/classNewtonsoft_1_1Json_1_1Tests_1_1TestObjects_1_1RequiredMembersClass.html',1,'Newtonsoft::Json::Tests::TestObjects']]],
  ['resolvercontractkey',['ResolverContractKey',['../d1/d84/structNewtonsoft_1_1Json_1_1Serialization_1_1ResolverContractKey.html',1,'Newtonsoft::Json::Serialization']]],
  ['resources',['Resources',['../d1/d67/classDataSiftControlPanel_1_1Properties_1_1Resources.html',1,'DataSiftControlPanel::Properties']]],
  ['resources',['Resources',['../d7/d11/classdatasift__examples_1_1Properties_1_1Resources.html',1,'datasift_examples::Properties']]],
  ['response',['Response',['../de/d6e/classNewtonsoft_1_1Json_1_1Tests_1_1Serialization_1_1JsonSerializerTest_1_1Response.html',1,'Newtonsoft::Json::Tests::Serialization::JsonSerializerTest']]],
  ['role',['Role',['../d5/d79/classNewtonsoft_1_1Json_1_1Tests_1_1LinqToSql_1_1Role.html',1,'Newtonsoft::Json::Tests::LinqToSql']]],
  ['rolemetadata',['RoleMetadata',['../d3/d06/classNewtonsoft_1_1Json_1_1Tests_1_1LinqToSql_1_1Role_1_1RoleMetadata.html',1,'Newtonsoft::Json::Tests::LinqToSql::Role']]],
  ['roletransfer',['RoleTransfer',['../d7/d0b/classNewtonsoft_1_1Json_1_1Tests_1_1TestObjects_1_1RoleTransfer.html',1,'Newtonsoft::Json::Tests::TestObjects']]]
];
