//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSiftTests.Account {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class AccountAPIResponses : global::System.Configuration.ApplicationSettingsBase {
        
        private static AccountAPIResponses defaultInstance = ((AccountAPIResponses)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AccountAPIResponses())));
        
        public static AccountAPIResponses Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\r\n   \"count\":12,\r\n   \"page\":1,\r\n   \"pages\":1,\r\n   \"per_page\":25,\r\n   \"identities" +
            "\":[\r\n      {\r\n         \"id\":\"a7e06ebce923e84c7817e91e07082113\",\r\n         \"label" +
            "\":\"facebook\",\r\n         \"api_key\":\"90c566d77e0179e0f051d3c9309e3f7b\",\r\n         " +
            "\"status\":\"active\",\r\n         \"master\":false,\r\n         \"created_at\":1429017449,\r" +
            "\n         \"updated_at\":1429017449,\r\n         \"expires_at\":null\r\n      },\r\n      " +
            "{\r\n         \"id\":\"4f98c56003d75a23ab68299ba969b45a\",\r\n         \"label\":\"facebook" +
            "2\",\r\n         \"api_key\":\"63933cc9e2a374b61bec122f0be60209\",\r\n         \"status\":\"" +
            "active\",\r\n         \"master\":false,\r\n         \"created_at\":1429017488,\r\n         " +
            "\"updated_at\":1429017488,\r\n         \"expires_at\":null\r\n      },\r\n      {\r\n       " +
            "  \"id\":\"ccfd5aa85ca83ee4f6da3935a122fa72\",\r\n         \"label\":\"test\",\r\n         \"" +
            "api_key\":\"06d4a72c94f4aef5cdabe41da6eaa452\",\r\n         \"status\":\"active\",\r\n     " +
            "    \"master\":false,\r\n         \"created_at\":1429099260,\r\n         \"updated_at\":14" +
            "29099260,\r\n         \"expires_at\":null\r\n      },\r\n      {\r\n         \"id\":\"bfdf35c" +
            "db423515e751771163f84f064\",\r\n         \"label\":\"test2\",\r\n         \"api_key\":\"6f3b" +
            "ff538467a684d99dbc9706df7708\",\r\n         \"status\":\"active\",\r\n         \"master\":f" +
            "alse,\r\n         \"created_at\":1429104353,\r\n         \"updated_at\":1429104353,\r\n   " +
            "      \"expires_at\":null\r\n      },\r\n      {\r\n         \"id\":\"aca47508c8f005e7e9c50" +
            "865d373fbe4\",\r\n         \"label\":\"test-1429105007\",\r\n         \"api_key\":\"5af0b644" +
            "17db3ae19e1866c4bee4f0fd\",\r\n         \"status\":\"active\",\r\n         \"master\":false" +
            ",\r\n         \"created_at\":1429105007,\r\n         \"updated_at\":1429105007,\r\n       " +
            "  \"expires_at\":null\r\n      },\r\n      {\r\n         \"id\":\"459d8844cb8b41f2f0a024318" +
            "b6209a3\",\r\n         \"label\":\"test-1429105056\",\r\n         \"api_key\":\"8a77664be4f3" +
            "0947f9da6762058874ad\",\r\n         \"status\":\"active\",\r\n         \"master\":false,\r\n " +
            "        \"created_at\":1429105056,\r\n         \"updated_at\":1429105056,\r\n         \"e" +
            "xpires_at\":null\r\n      },\r\n      {\r\n         \"id\":\"2845944a18c76711c834221bdd652" +
            "f09\",\r\n         \"label\":\"test-1429105077\",\r\n         \"api_key\":\"22f2b0bfea21f7f4" +
            "e5107f45a9933ad9\",\r\n         \"status\":\"active\",\r\n         \"master\":false,\r\n     " +
            "    \"created_at\":1429105077,\r\n         \"updated_at\":1429105077,\r\n         \"expir" +
            "es_at\":null\r\n      },\r\n      {\r\n         \"id\":\"6350457a5a0a0bfbd7ba81bfcde5e358\"" +
            ",\r\n         \"label\":\"test-1429105163\",\r\n         \"api_key\":\"1814d8009d8ab092886f" +
            "3dc640f6bb50\",\r\n         \"status\":\"active\",\r\n         \"master\":false,\r\n         " +
            "\"created_at\":1429105163,\r\n         \"updated_at\":1429105163,\r\n         \"expires_a" +
            "t\":null\r\n      },\r\n      {\r\n         \"id\":\"19e7479f2f9ec4bb02e40ed3a8faa708\",\r\n " +
            "        \"label\":\"test-1429105170\",\r\n         \"api_key\":\"3e24e2b6d5ff4dd4bf8d3e30" +
            "2044e3df\",\r\n         \"status\":\"active\",\r\n         \"master\":false,\r\n         \"cre" +
            "ated_at\":1429105170,\r\n         \"updated_at\":1429105170,\r\n         \"expires_at\":n" +
            "ull\r\n      },\r\n      {\r\n         \"id\":\"28929e03498f7f6838a7d6aae0f5ed45\",\r\n     " +
            "    \"label\":\"test-1429105197\",\r\n         \"api_key\":\"d04d3da419dc3d5e128ae509d875" +
            "d399\",\r\n         \"status\":\"active\",\r\n         \"master\":false,\r\n         \"created" +
            "_at\":1429105197,\r\n         \"updated_at\":1429105197,\r\n         \"expires_at\":null\r" +
            "\n      },\r\n      {\r\n         \"id\":\"4c8a13559524d7138756bc0892263966\",\r\n         " +
            "\"label\":\"test-1429105230\",\r\n         \"api_key\":\"ab86f3f63cb966b552571cba97fbf206" +
            "\",\r\n         \"status\":\"active\",\r\n         \"master\":false,\r\n         \"created_at\"" +
            ":1429105230,\r\n         \"updated_at\":1429105230,\r\n         \"expires_at\":null\r\n   " +
            "   },\r\n      {\r\n         \"id\":\"36b4d8e701a0f2afc84c4afb4153135e\",\r\n         \"lab" +
            "el\":\"test-1429105353\",\r\n         \"api_key\":\"83e10c3074303bdfc91928f6076f91bf\",\r\n" +
            "         \"status\":\"active\",\r\n         \"master\":false,\r\n         \"created_at\":142" +
            "9105353,\r\n         \"updated_at\":1429105353,\r\n         \"expires_at\":null\r\n      }" +
            "\r\n   ]\r\n}")]
        public string Identity_Get {
            get {
                return ((string)(this["Identity_Get"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"id\":\"f3865ceea4bac3f7eec0ea12d7e83508\",\"label\":\"Customer 1\",\"api_key\":\"628aefca" +
            "da278cb8288f47aa69e176f5\",\"status\":\"active\",\"master\":false,\"created_at\":14296957" +
            "63,\"updated_at\":1429695763,\"expires_at\":null}")]
        public string Identity_Create {
            get {
                return ((string)(this["Identity_Create"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\r\n   \"id\":\"f3865ceea4bac3f7eec0ea12d7e83508\",\r\n   \"label\":\"Customer 1\",\r\n   \"api" +
            "_key\":\"628aefcada278cb8288f47aa69e176f5\",\r\n   \"status\":\"active\",\r\n   \"master\":fa" +
            "lse,\r\n   \"created_at\":1429695763,\r\n   \"updated_at\":1429695763,\r\n   \"expires_at\":" +
            "null\r\n}")]
        public string Identity_Get_Id {
            get {
                return ((string)(this["Identity_Get_Id"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
   ""count"":1,
   ""page"":1,
   ""pages"":1,
   ""per_page"":25,
   ""identities"":[
      {
         ""id"":""f3865ceea4bac3f7eec0ea12d7e83508"",
         ""label"":""Customer 1"",
         ""api_key"":""628aefcada278cb8288f47aa69e176f5"",
         ""status"":""active"",
         ""master"":false,
         ""created_at"":1429695763,
         ""updated_at"":1429695763,
         ""expires_at"":null
      }
   ]
}")]
        public string Identity_Get_Label {
            get {
                return ((string)(this["Identity_Get_Label"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
   ""count"":23,
   ""page"":1,
   ""pages"":12,
   ""per_page"":2,
   ""identities"":[
      {
         ""id"":""a7e06ebce923e84c7817e91e07082113"",
         ""label"":""facebook"",
         ""api_key"":""90c566d77e0179e0f051d3c9309e3f7b"",
         ""status"":""active"",
         ""master"":false,
         ""created_at"":1429017449,
         ""updated_at"":1429017449,
         ""expires_at"":null
      },
      {
         ""id"":""4f98c56003d75a23ab68299ba969b45a"",
         ""label"":""facebook2"",
         ""api_key"":""63933cc9e2a374b61bec122f0be60209"",
         ""status"":""active"",
         ""master"":false,
         ""created_at"":1429017488,
         ""updated_at"":1429017488,
         ""expires_at"":null
      }
   ]
}")]
        public string Identity_Get_Page {
            get {
                return ((string)(this["Identity_Get_Page"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"id\":\"f3865ceea4bac3f7eec0ea12d7e83508\",\"label\":\"Customer 1\",\"api_key\":\"628aefca" +
            "da278cb8288f47aa69e176f5\",\"status\":\"active\",\"master\":false,\"created_at\":14296957" +
            "63,\"updated_at\":1429695763,\"expires_at\":null}")]
        public string Identity_Update {
            get {
                return ((string)(this["Identity_Update"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"service\":\"facebook\",\"token\":\"fed85f6b316fb18930ee28e8754f4963\",\"created_at\":142" +
            "9781734,\"updated_at\":1429781734,\"expires_at\":null}")]
        public string Token_Create {
            get {
                return ((string)(this["Token_Create"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"count\":1,\"page\":1,\"pages\":1,\"per_page\":25,\"tokens\":[{\"service\":\"facebook\",\"toke" +
            "n\":\"fed85f6b316fb18930ee28e8754f4963\",\"created_at\":1429781734,\"updated_at\":14297" +
            "81734,\"expires_at\":null}]}")]
        public string Token_GetAll {
            get {
                return ((string)(this["Token_GetAll"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\r\n   \"service\":\"facebook\",\r\n   \"token\":\"ddd85f6b316fb18930ee28e8754f4963\",\r\n   \"" +
            "created_at\":1429781734,\r\n   \"updated_at\":1429781734,\r\n   \"expires_at\":null\r\n}")]
        public string Token_Update {
            get {
                return ((string)(this["Token_Update"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"id\":\"e1e0a598176cf0bcb159f26dc9a8744d\",\"service\":\"facebook\",\"total_allowance\":1" +
            "00000, \"analyze_queries\": 500}")]
        public string Limit_Create {
            get {
                return ((string)(this["Limit_Create"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"id\":\"e1e0a598176cf0bcb159f26dc9a8744d\",\"service\":\"facebook\",\"total_allowance\":1" +
            "00000, \"analyze_queries\": 500}")]
        public string Limit_GetByIdentityAndService {
            get {
                return ((string)(this["Limit_GetByIdentityAndService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
  ""count"": 2,
  ""page"": 1,
  ""pages"": 1,
  ""per_page"": 25,
  ""limits"": [
    {
      ""id"": ""a7e06ebce923e84c7817e91e07082113"",
      ""service"": ""facebook"",
      ""total_allowance"": 20000
    },
    {
      ""id"": ""e1e0a598176cf0bcb159f26dc9a8744d"",
      ""service"": ""facebook"",
      ""total_allowance"": 100000
    }
  ]
}")]
        public string Limit_AllByService {
            get {
                return ((string)(this["Limit_AllByService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"id\":\"e1e0a598176cf0bcb159f26dc9a8744d\",\"service\":\"facebook\",\"total_allowance\":2" +
            "00000, \"analyze_queries\": 600}")]
        public string Limit_Update {
            get {
                return ((string)(this["Limit_Update"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
  ""usage"": [
    {
      ""quantity"": 0.02312,
      ""cost"": 0,
      ""category"": ""managed_sources"",
      ""unit"": ""dpu"",
      ""source"": ""facebook_pages"",
      ""timestamp"": 1445346000
    },
    {
      ""quantity"": 0.03332,
      ""cost"": 0,
      ""category"": ""realtime"",
      ""unit"": ""dpu"",
      ""source"": """",
      ""timestamp"": 1445346000
    }
  ]
}")]
        public string Account_Usage {
            get {
                return ((string)(this["Account_Usage"]));
            }
        }
    }
}
