//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSiftTests {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class MockAPIResponses : global::System.Configuration.ApplicationSettingsBase {
        
        private static MockAPIResponses defaultInstance = ((MockAPIResponses)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MockAPIResponses())));
        
        public static MockAPIResponses Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\r\n    \"created_at\":\"2011-05-12 11:18:07\",\r\n    \"dpu\":\"0.1\"\r\n}")]
        public string Validate {
            get {
                return ((string)(this["Validate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\r\n    \"hash\": \"9fe133a7ee1bd2757f1e26bd78342458\",\r\n    \"created_at\": \"2011-05-12" +
            " 11:18:07\",\r\n    \"dpu\": \"0.1\"\r\n}")]
        public string Compile {
            get {
                return ((string)(this["Compile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
   ""start"": ""Mon, 07 Nov 2011 11:15:00 +0000"",
   ""end"": ""Mon, 07 Nov 2011 12:15:00 +0000"",
   ""streams"": {
       ""693f5134c73a62ed85ef271040bf266b"": {
            ""licenses"": {
                ""facebook"":365,
                ""twitter"":18062
            },
            ""seconds"": 3600
       },
       ""14af4134c73a62ed65ef1f1040bf321e"": {
            ""licenses"": {
                ""facebook"":344,
                ""twitter"":26062
            },
            ""seconds"": 3900
       }
   }
}")]
        public string Usage {
            get {
                return ((string)(this["Usage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
   ""dpu"": 0.2,
   ""detail"": {
       ""contains"": {
           ""count"": 2,
           ""dpu"": 0.2,
           ""targets"": {
               ""interaction.content"": {
                   ""count"": 1,
                   ""dpu"": 0.1
               },
               ""interaction.title"": {
                   ""count"": 1,
                   ""dpu"": 0.1
               }
           }
       }
   }
}")]
        public string DPU {
            get {
                return ((string)(this["DPU"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
  ""balance"": {
    ""plan"": ""subscription"",
    ""threshold"": 20000,
    ""allowances"": [
      {
        ""name"": ""DPU Usage Plan"",
        ""categories"": [
          ""realtime"",
          ""managed_sources"",
          ""historics"",
          ""historicpreview""
        ],
        ""cost"": 0,
        ""allowance"": 100000,
        ""remaining"": 71030.16,
        ""usage"": 28969.84
      },
      {
        ""name"": ""BoardReader allowance"",
        ""categories"": [],
        ""cost"": 0,
        ""allowance"": 200000,
        ""remaining"": 100000,
        ""usage"": 100000
      }
    ]
  }
}")]
        public string Balance {
            get {
                return ((string)(this["Balance"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
    ""data"": [
        {
            ""id"": ""6b42f539793a02bfd68c"",
            ""definition_id"": ""6beacf0faeb77c974ab801733ed2c597"",
            ""name"": ""twitter"",
            ""start"": 1274742000,
            ""end"": 1339110000,
            ""created_at"": 1339147632,
            ""status"": ""init"",
            ""progress"": 0,
            ""sources"": [
                ""facebook"",
                ""twitter""
            ],
            ""sample"": 100
        },
        {
            ""id"": ""fdf6652ac82206358eab"",
            ""definition_id"": ""93558e17de15072fa126370c37c5bd8f"",
            ""name"": ""test"",
            ""start"": 1337040000,
            ""end"": 1337126400,
            ""created_at"": 1337161927,
            ""status"": ""succeeded"",
            ""progress"": 100,
            ""sources"": [
                """"
            ],
            ""sample"": 100
        }
    ],
    ""count"": 79
}")]
        public string HistoricsGet {
            get {
                return ((string)(this["HistoricsGet"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
    ""dpus"": 234.6916666667,
    ""id"": ""4ef7c852a96d6352764f"",
    ""availability"": {
        ""start"": 1341673200,
        ""end"": 1341759600,
        ""sources"": {
            ""twitter"": {
                ""status"": 99,
                ""versions"": [
                    3
                ],
                ""augmentations"": {
                    ""klout"": 50,
                    ""links"": 100
                }
            },
            ""facebook"": {
                ""status"": 99,
                ""versions"": [
                    2,
                    3
                ],
                ""augmentations"": {
                    ""links"": 95
                }
            }
        }
    }
}")]
        public string HistoricsPrepare {
            get {
                return ((string)(this["HistoricsPrepare"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
    ""id"": ""9e97d9ac115e58fcb7ab"",
    ""definition_id"": ""e4d0b9bb266e8f3f2de405f6c1a2de23"",
    ""name"": ""historics-get-test"",
    ""start"": 1325376001,
    ""end"": 1325894401,
    ""created_at"": 1363271961,
    ""status"": ""running"",
    ""progress"": 15,
    ""sources"": [
        ""twitter""
    ],
    ""sample"": 100,
    ""chunks"": [
        {
            ""status"": ""succeeded"",
            ""progress"": 100,
            ""start_time"": 1325376001,
            ""end_time"": 1325462400
        },
        {
            ""status"": ""running"",
            ""progress"": 5,
            ""start_time"": 1325462400,
            ""end_time"": 1325548800
        },
        {
            ""status"": ""init"",
            ""progress"": 0,
            ""start_time"": 1325548800,
            ""end_time"": 1325635200
        },
        {
            ""status"": ""init"",
            ""progress"": 0,
            ""start_time"": 1325635200,
            ""end_time"": 1325721600
        },
        {
            ""status"": ""init"",
            ""progress"": 0,
            ""start_time"": 1325721600,
            ""end_time"": 1325808000
        },
        {
            ""status"": ""init"",
            ""progress"": 0,
            ""start_time"": 1325808000,
            ""end_time"": 1325894400
        },
        {
            ""status"": ""init"",
            ""progress"": 0,
            ""start_time"": 1325894400,
            ""end_time"": 1325894401
        }
    ]
}")]
        public string HistoricsGetById {
            get {
                return ((string)(this["HistoricsGetById"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
    ""data"": [
        {
            ""id"": ""6b42f539793a02bfd68c"",
            ""definition_id"": ""6beacf0faeb77c974ab801733ed2c597"",
            ""name"": ""twitter"",
            ""start"": 1274742000,
            ""end"": 1339110000,
            ""created_at"": 1339147632,
            ""status"": ""init"",
            ""progress"": 0,
            ""sources"": [
                ""facebook"",
                ""twitter""
            ],
            ""sample"": 100
        }
    ],
    ""count"": 79
}")]
        public string HistoricsGetMax1 {
            get {
                return ((string)(this["HistoricsGetMax1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\r\n    \"id\": \"9e97d9ac115e58fcb7ab\",\r\n    \"definition_id\": \"cdd0b9bb266e8f3f2de40" +
            "5f6c1a2b23e\",\r\n    \"name\": \"job-estimation-test\",\r\n    \"start\": 1325376001,\r\n   " +
            " \"end\": 1325894401,\r\n    \"created_at\": 1363271961,\r\n    \"status\": \"running\",\r\n  " +
            "  \"progress\": 15,\r\n    \"sources\": [\r\n        \"twitter\"\r\n    ],\r\n    \"sample\": 10" +
            "0,\r\n    \"volume_info\": {\r\n        \"twitter\": 1448591013\r\n    },\r\n    \"chunks\": [" +
            "\r\n        {\r\n            \"status\": \"succeeded\",\r\n            \"progress\": 100,\r\n " +
            "           \"start_time\": 1325376001,\r\n            \"end_time\": 1325462400,\r\n     " +
            "       \"estimated_completion\": 1363274434\r\n        },\r\n        {\r\n            \"s" +
            "tatus\": \"running\",\r\n            \"progress\": 5,\r\n            \"start_time\": 132546" +
            "2400,\r\n            \"end_time\": 1325548800,\r\n            \"estimated_completion\": " +
            "1363277434\r\n        },\r\n        {\r\n            \"status\": \"init\",\r\n            \"p" +
            "rogress\": 0,\r\n            \"start_time\": 1325548800,\r\n            \"end_time\": 132" +
            "5635200,\r\n            \"estimated_completion\": 1363285834\r\n        },\r\n        {\r" +
            "\n            \"status\": \"init\",\r\n            \"progress\": 0,\r\n            \"start_t" +
            "ime\": 1325635200,\r\n            \"end_time\": 1325721600,\r\n            \"estimated_c" +
            "ompletion\": 1363279834\r\n        },\r\n        {\r\n            \"status\": \"init\",\r\n  " +
            "          \"progress\": 0,\r\n            \"start_time\": 1325721600,\r\n            \"en" +
            "d_time\": 1325808000,\r\n            \"estimated_completion\": 1363282234\r\n        }," +
            "\r\n        {\r\n            \"status\": \"init\",\r\n            \"progress\": 0,\r\n        " +
            "    \"start_time\": 1325808000,\r\n            \"end_time\": 1325894400,\r\n            " +
            "\"estimated_completion\": 1363284034\r\n        },\r\n        {\r\n            \"status\":" +
            " \"init\",\r\n            \"progress\": 0,\r\n            \"start_time\": 1325894400,\r\n   " +
            "         \"end_time\": 1325894401,\r\n            \"estimated_completion\": 1363287634" +
            "\r\n        }\r\n    ],\r\n    \"estimated_completion\": 1363287634\r\n}")]
        public string HistoricsGetWithCompletion {
            get {
                return ((string)(this["HistoricsGetWithCompletion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"[
    {
        ""start"": ""1325376000"",
        ""end"": 1325462400,
        ""sources"": {
            ""twitter"": {
                ""augmentations"": {
                    ""demographic"": 100,
                    ""klout"": 100,
                    ""language"": 100,
                    ""links"": 100,
                    ""salience"": 100,
                    ""trends"": 100
                },
                ""versions"": [
                    ""1""
                ],
                ""status"": 100
            }
        }
    },
    {
        ""start"": ""1325462400"",
        ""end"": 1325548800,
        ""sources"": {
            ""twitter"": {
                ""augmentations"": {
                    ""demographic"": 100,
                    ""klout"": 100,
                    ""language"": 100,
                    ""links"": 100,
                    ""salience"": 100,
                    ""trends"": 100
                },
                ""versions"": [
                    ""1""
                ],
                ""status"": 100
            }
        }
    }
]")]
        public string HistoricsStatus {
            get {
                return ((string)(this["HistoricsStatus"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
    ""count"": 2,
    ""subscriptions"": [
        {
            ""id"": ""d668655cfe5f93741ddcd30bb309a8c7"",
            ""output_type"": ""dynamodb"",
            ""name"": ""mypushsubscription1"",
            ""created_at"": 1365430066,
            ""hash"": ""42d388f8b1db997faaf7dab487f11290"",
            ""hash_type"": ""stream"",
            ""output_params"": {
                ""table"": ""datasift-dynamodb"",
                ""region"": ""dynamodb.eu-west-1.amazonaws.com""
            },
            ""status"": ""active"",
            ""last_request"": null,
            ""last_success"": null,
            ""remaining_bytes"": null,
            ""lost_data"": false,
            ""start"": 0,
            ""end"": 0
        },
        {
            ""id"": ""d468655cfe5f93741ddcd30bb309a8c7"",
            ""output_type"": ""dynamodb"",
            ""name"": ""mypushsubscription2"",
            ""created_at"": 1365430066,
            ""hash"": ""42d388f8b1db997faaf7dab487f11290"",
            ""hash_type"": ""stream"",
            ""output_params"": {
                ""table"": ""datasift-dynamodb"",
                ""region"": ""dynamodb.eu-west-1.amazonaws.com""
            },
            ""status"": ""active"",
            ""last_request"": null,
            ""last_success"": null,
            ""remaining_bytes"": null,
            ""lost_data"": false,
            ""start"": 0,
            ""end"": 0
        }
    ]
}")]
        public string PushGet {
            get {
                return ((string)(this["PushGet"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
    ""id"": ""d468655cfe5f93741ddcd30bb309a8c7"",
    ""output_type"": ""dynamodb"",
    ""name"": ""mypushsubscription1"",
    ""created_at"": 1365430066,
    ""hash"": ""42d388f8b1db997faaf7dab487f11290"",
    ""hash_type"": ""stream"",
    ""output_params"": {
        ""table"": ""datasift-dynamodb"",
        ""region"": ""dynamodb.eu-west-1.amazonaws.com""
    },
    ""status"": ""active"",
    ""last_request"": null,
    ""last_success"": null,
    ""remaining_bytes"": null,
    ""lost_data"": false,
    ""start"": 0,
    ""end"": 0
}")]
        public string PushGetById {
            get {
                return ((string)(this["PushGetById"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
    ""subscriptions"": [
        {
            ""id"": ""3a5c2546136a037d4b2df0b8b8836f3e"",
            ""output_type"": ""pull"",
            ""name"": ""Example historics subscription"",
            ""created_at"": 1405333439,
            ""user_id"": 27360,
            ""hash"": ""6cd38099f4c1e0f1ac31"",
            ""hash_type"": ""historic"",
            ""output_params"": [],
            ""status"": ""active"",
            ""last_request"": null,
            ""last_success"": null,
            ""remaining_bytes"": null,
            ""lost_data"": false,
            ""start"": 1405333439,
            ""end"": null
        }
    ],
    ""count"": 1
}")]
        public string PushGetByHistoricsId {
            get {
                return ((string)(this["PushGetByHistoricsId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
    ""subscriptions"": [
        {
            ""id"": ""03b9f2e18503afd6d0c0d3bf76c14224"",
            ""output_type"": ""pull"",
            ""name"": ""Example pull subscription"",
            ""created_at"": 1405333664,
            ""user_id"": 27360,
            ""hash"": ""13e9347e7da32f19fcdb08e297019d2e"",
            ""hash_type"": ""stream"",
            ""output_params"": [],
            ""status"": ""finishing"",
            ""last_request"": 1405333669,
            ""last_success"": 1405333669,
            ""remaining_bytes"": null,
            ""lost_data"": false,
            ""start"": 1405333664,
            ""end"": 1405333670
        }
    ],
    ""count"": 1
}")]
        public string PushGetByHash {
            get {
                return ((string)(this["PushGetByHash"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
    ""subscriptions"": [
        {
            ""id"": ""3a5c2546136a037d4b2df0b8b8836f3e"",
            ""output_type"": ""pull"",
            ""name"": ""Example historics subscription"",
            ""created_at"": 1405333439,
            ""user_id"": 27360,
            ""hash"": ""6cd38099f4c1e0f1ac31"",
            ""hash_type"": ""historic"",
            ""output_params"": [],
            ""status"": ""active"",
            ""last_request"": null,
            ""last_success"": null,
            ""remaining_bytes"": null,
            ""lost_data"": false,
            ""start"": 1405333439,
            ""end"": null
        }
    ],
    ""count"": 2
}")]
        public string PushGetPage {
            get {
                return ((string)(this["PushGetPage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
    ""id"": ""d468655cfe5f93741ddcd30bb309a8c7"",
    ""output_type"": ""pull"",
    ""name"": ""New subscription"",
    ""created_at"": 1365430066,
    ""user_id"": 12635,
    ""hash"": ""42d388f8b1db997faaf7dab487f11290"",
    ""hash_type"": ""stream"",
    ""status"": ""active"",
    ""last_request"": null,
    ""last_success"": null,
    ""remaining_bytes"": null,
    ""lost_data"": false,
    ""start"": 0,
    ""end"": 1435671577
}")]
        public string PushCreate {
            get {
                return ((string)(this["PushCreate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
    ""id"": ""d468655cfe5f93741ddcd30bb309a8c7"",
    ""output_type"": ""dynamodb"",
    ""name"": ""mypushsubscription"",
    ""created_at"": 1365430066,
    ""user_id"": 12635,
    ""hash"": ""0dddb9bb2f6e8f3f2de405f6c1a2b21e"",
    ""hash_type"": ""stream"",
    ""output_params"": {
        ""region"": ""dynamodb.eu-west-1.amazonaws.com"",
        ""bucket"": ""datasift-s3"",
        ""directory"": ""interactions"",
        ""acl"": ""private"",
        ""delivery_frequency"": 60,
        ""max_size"": 102400,
        ""file_prefix"": ""Datasift""
    },
    ""status"": ""finishing"",
    ""last_request"": 1365438298,
    ""last_success"": 1365435315,
    ""remaining_bytes"": null,
    ""lost_data"": false,
    ""start"": null,
    ""end"": null
}")]
        public string PushStop {
            get {
                return ((string)(this["PushStop"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
    ""id"": ""d468655cfe5f93741ddcd30bb309a8c7"",
    ""output_type"": ""dynamodb"",
    ""name"": ""mypushsubscription"",
    ""created_at"": 1365430066,
    ""user_id"": 12635,
    ""hash"": ""0dddb9bb2f6e8f3f2de405f6c1a2b21e"",
    ""hash_type"": ""stream"",
    ""output_params"": {
        ""region"": ""dynamodb.eu-west-1.amazonaws.com"",
        ""bucket"": ""datasift-s3"",
        ""directory"": ""interactions"",
        ""acl"": ""private"",
        ""delivery_frequency"": 60,
        ""max_size"": 102400,
        ""file_prefix"": ""Datasift""
    },
    ""status"": ""paused"",
    ""last_request"": 1365438298,
    ""last_success"": 1365435315,
    ""remaining_bytes"": null,
    ""lost_data"": false,
    ""start"": null,
    ""end"": null
}")]
        public string PushPause {
            get {
                return ((string)(this["PushPause"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
    ""id"": ""d468655cfe5f93741ddcd30bb309a8c7"",
    ""output_type"": ""dynamodb"",
    ""name"": ""mypushsubscription"",
    ""created_at"": 1365430066,
    ""user_id"": 12635,
    ""hash"": ""0dddb9bb2f6e8f3f2de405f6c1a2b21e"",
    ""hash_type"": ""stream"",
    ""output_params"": {
        ""region"": ""dynamodb.eu-west-1.amazonaws.com"",
        ""bucket"": ""datasift-s3"",
        ""directory"": ""interactions"",
        ""acl"": ""private"",
        ""delivery_frequency"": 60,
        ""max_size"": 102400,
        ""file_prefix"": ""Datasift""
    },
    ""status"": ""active"",
    ""last_request"": 1365438298,
    ""last_success"": 1365435315,
    ""remaining_bytes"": null,
    ""lost_data"": false,
    ""start"": null,
    ""end"": null
}")]
        public string PushResume {
            get {
                return ((string)(this["PushResume"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
    ""success"": true,
    ""count"": 8740,
    ""log_entries"": [
        {
            ""subscription_id"": ""4b7ce39a5292b96ccd98f69324b0dc99"",
            ""success"": true,
            ""request_time"": 1344859261,
            ""message"": ""The delivery has completed""
        },
        {
            ""subscription_id"": ""13ba92f6784da5e60b82f532f43c7d17"",
            ""success"": false,
            ""request_time"": 1344855061,
            ""message"": ""The delivery was paused for too long""
        },
        {
            ""subscription_id"": ""4e097f46ef0dd2e8e3f25f84dddda775"",
            ""success"": false,
            ""request_time"": 1344630221,
            ""message"": ""Stopped due to too many failed delivery attempts""
        },
        {
            ""subscription_id"": ""4e097f46ef0dd2e8e3f25f84dddda775"",
            ""success"": false,
            ""request_time"": 1344630221,
            ""message"": ""The endpoint returned a 500 internal server error""
        }
    ]
}")]
        public string PushLog {
            get {
                return ((string)(this["PushLog"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
    ""success"": true,
    ""count"": 8740,
    ""log_entries"": [
        {
            ""request_time"": 1342436365,
            ""success"": true,
            ""subscription_id"": ""d468655cfe5f93741ddcd30bb309a8c7""
        },
        {
            ""request_time"": 1342436361,
            ""success"": true,
            ""subscription_id"": ""d468655cfe5f93741ddcd30bb309a8c7""
        },
        {
            ""request_time"": 1342436255,
            ""success"": true,
            ""subscription_id"": ""d468655cfe5f93741ddcd30bb309a8c7""
        }
    ]
}")]
        public string PushLogById {
            get {
                return ((string)(this["PushLogById"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
    ""success"": true,
    ""count"": 182,
    ""log_entries"": [
        {
            ""request_time"": 1405337430,
            ""success"": true,
            ""subscription_id"": ""03b9f2e18503afd6d0c0d3bf76c14224"",
            ""message"": ""No requests were made for this subscription in over 1 hour(s) ago""
        },
        {
            ""request_time"": 1405337430,
            ""success"": true,
            ""subscription_id"": ""03b9f2e18503afd6d0c0d3bf76c14224"",
            ""message"": ""The status has changed to: finished""
        },
        {
            ""request_time"": 1405333670,
            ""success"": true,
            ""subscription_id"": ""03b9f2e18503afd6d0c0d3bf76c14224"",
            ""message"": ""The status has changed to: finishing""
        },
        {
            ""request_time"": 1404300353,
            ""success"": true,
            ""subscription_id"": ""ce3c55c2acf55e82fb665d4a7201fbaf"",
            ""message"": ""The status has changed to: deleted""
        },
        {
            ""request_time"": 1404212291,
            ""success"": true,
            ""subscription_id"": ""645c959027328905713cdd64eb35f10d"",
            ""message"": ""The status has changed to: deleted""
        }
    ]
}")]
        public string PushLogPage {
            get {
                return ((string)(this["PushLogPage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
    ""id"": ""f4d4caee9acfd27faf88843d8d6191b1"",
    ""output_type"": ""dynamodb"",
    ""name"": ""new name"",
    ""created_at"": 1365430066,
    ""user_id"": 12635,
    ""hash"": ""edd0b9fb266e8f3f2de40bf6c1a2bf3e"",
    ""hash_type"": ""stream"",
    ""output_params"": {
        ""table"": ""datasift-dynamodb"",
        ""region"": ""dynamodb.us-west-1.amazonaws.com""
    },
    ""status"": ""active"",
    ""last_request"": 1365437678,
    ""last_success"": 1365435315,
    ""remaining_bytes"": 14945919,
    ""lost_data"": false,
    ""start"": null,
    ""end"": null
}")]
        public string PushUpdate {
            get {
                return ((string)(this["PushUpdate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\r\n    \"id\": \"93186020677f1881aab7cddb28fa805c\",\r\n    \"hash\": \"c426dd575d435e5bc6" +
            "8a6edf125026c4\",\r\n    \"hash_type\": \"stream\",\r\n    \"count\": 2,\r\n    \"delivered_at" +
            "\": \"Fri, 17 Aug 2012 14:23:00 +0000\",\r\n    \"interactions\": [\r\n        {\r\n       " +
            "     \"interaction\": {\r\n                \"source\": \"web\",\r\n                \"author" +
            "\": {\r\n                    \"username\": \"johndoe\",\r\n                    \"name\": \"J" +
            "ohn Doe\",\r\n                    \"id\": 10750902,\r\n                    \"avatar\": \"h" +
            "ttp://a0.twimg.com/profile_images/1111111111/example.jpeg\",\r\n                   " +
            " \"link\": \"http://twitter.com/johndoe\"\r\n                },\r\n                \"type" +
            "\": \"twitter\",\r\n                \"created_at\": \"Fri, 17 Aug 2012 14:13:08 +0000\",\r" +
            "\n                \"content\": \"I like ice cream!\",\r\n                \"id\": \"1e1e875" +
            "ab43fa233e074337458bc1dca\",\r\n                \"link\": \"http://twitter.com/johndoe" +
            "/statuses/111111111111111111\",\r\n                \"geo\": {\r\n                    \"l" +
            "atitude\": 42.376104,\r\n                    \"longitude\": -71.237189\r\n             " +
            "   }\r\n            },\r\n            \"twitter\": {\r\n                \"created_at\": \"F" +
            "ri, 17 Aug 2012 14:13:08 +0000\",\r\n                \"domains\": [\r\n                " +
            "    \"4sq.com\"\r\n                ],\r\n                \"geo\": {\r\n                   " +
            " \"latitude\": 42.376104,\r\n                    \"longitude\": -71.237189\r\n          " +
            "      },\r\n                \"id\": \"111111111111111111\",\r\n                \"links\": " +
            "[\r\n                    \"http://4sq.com/NLM3gD\"\r\n                ],\r\n            " +
            "    \"mentions\": [\r\n                    \"beyonce\",\r\n                    \"ladygaga" +
            "\"\r\n                ],\r\n                \"place\": {\r\n                    \"id\": \"90" +
            "ad0a08b3333d6d\",\r\n                    \"url\": \"http://api.twitter.com/1/geo/id/ex" +
            "ample.json\",\r\n                    \"place_type\": \"poi\",\r\n                    \"cou" +
            "ntry\": \"United States\",\r\n                    \"country_code\": \"US\",\r\n            " +
            "        \"full_name\": \"Cafe On the Common, Waltham\",\r\n                    \"name\":" +
            " \"Cafe On the Common\"\r\n                },\r\n                \"source\": \"<a href=\\\"" +
            "http://example.com\\\" rel=\\\"nofollow\\\">example</a>\",\r\n                \"text\": \"I " +
            "like ice cream\",\r\n                \"user\": {\r\n                    \"name\": \"John D" +
            "oe\",\r\n                    \"url\": \"http://about.me/John Doe\",\r\n                  " +
            "  \"description\": \"all my tweets...\",\r\n                    \"location\": \"London\",\r" +
            "\n                    \"statuses_count\": 9689,\r\n                    \"followers_cou" +
            "nt\": 2054,\r\n                    \"friends_count\": 2016,\r\n                    \"scr" +
            "een_name\": \"johndoe\",\r\n                    \"lang\": \"en\",\r\n                    \"t" +
            "ime_zone\": \"Eastern Time (US & Canada)\",\r\n                    \"utc_offset\": -180" +
            "00,\r\n                    \"listed_count\": 118,\r\n                    \"id\": 1111111" +
            "1,\r\n                    \"id_str\": \"11111111\",\r\n                    \"geo_enabled\"" +
            ": true,\r\n                    \"created_at\": \"Fri, 30 Nov 2007 21:26:38 +0000\"\r\n  " +
            "              }\r\n            }\r\n        },\r\n        {\r\n            \"demographic\"" +
            ": {\r\n                \"gender\": \"mostly_male\"\r\n            },\r\n            \"inter" +
            "action\": {\r\n                \"source\": \"example\",\r\n                \"author\": {\r\n " +
            "                   \"username\": \"JohnDoe\",\r\n                    \"name\": \"John Doe" +
            "\",\r\n                    \"id\": 11111111,\r\n                    \"avatar\": \"http://a" +
            "0.twimg.com/profile_images/1111111111/example.jpg\",\r\n                    \"link\":" +
            " \"http://twitter.com/JohnDoe\"\r\n                },\r\n                \"type\": \"twit" +
            "ter\",\r\n                \"created_at\": \"Fri, 17 Aug 2012 14:13:09 +0000\",\r\n       " +
            "         \"content\": \"I love ice cream!\",\r\n                \"id\": \"1a1a1a1a1a1a1a1" +
            "a1a1a1a1a1a1a1a1a\",\r\n                \"link\": \"http://twitter.com/JohnDoe/statuse" +
            "s/111111111111111111\",\r\n                \"geo\": {\r\n                    \"latitude\"" +
            ": 41.48454863,\r\n                    \"longitude\": -72.79693173\r\n                }" +
            "\r\n            },\r\n            \"twitter\": {\r\n                \"created_at\": \"Fri, " +
            "17 Aug 2012 14:13:09 +0000\",\r\n                \"domains\": [\r\n                    " +
            "\"4sq.com\"\r\n                ],\r\n                \"geo\": {\r\n                    \"la" +
            "titude\": 41.48454863,\r\n                    \"longitude\": -72.79693173\r\n          " +
            "      },\r\n                \"id\": \"111111111111111111\",\r\n                \"links\": " +
            "[\r\n                    \"http://4sq.com/NMH47L\"\r\n                ],\r\n            " +
            "    \"place\": {\r\n                    \"id\": \"e5ac52573b5f3333\",\r\n                 " +
            "   \"url\": \"http://api.twitter.com/1/geo/id/1a1a1a1a1a1a1a1a.json\",\r\n            " +
            "        \"place_type\": \"poi\",\r\n                    \"country\": \"United States\",\r\n " +
            "                   \"country_code\": \"US\",\r\n                    \"full_name\": \"Will" +
            "ow Farm\",\r\n                    \"name\": \"Willow Farm\"\r\n                },\r\n      " +
            "          \"source\": \"<a href=\\\"http://example.com\\\" rel=\\\"nofollow\\\">example</a>" +
            "\",\r\n                \"text\": \"I love ice cream\",\r\n                \"user\": {\r\n    " +
            "                \"name\": \"John Doe\",\r\n                    \"description\": \"Man of " +
            "mystery\\n\",\r\n                    \"location\": \"Main street\",\r\n                   " +
            " \"statuses_count\": 10073,\r\n                    \"followers_count\": 444,\r\n        " +
            "            \"friends_count\": 533,\r\n                    \"screen_name\": \"John Doe\"" +
            ",\r\n                    \"lang\": \"en\",\r\n                    \"time_zone\": \"Quito\",\r" +
            "\n                    \"utc_offset\": -18000,\r\n                    \"listed_count\": " +
            "9,\r\n                    \"id\": 11111111,\r\n                    \"id_str\": \"11111111" +
            "\",\r\n                    \"geo_enabled\": true,\r\n                    \"created_at\": " +
            "\"Sun, 26 Apr 2009 23:38:45 +0000\"\r\n                }\r\n            }\r\n        }\r\n" +
            "    ]\r\n}")]
        public string PullJsonMetaFormat {
            get {
                return ((string)(this["PullJsonMetaFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[\r\n    {\r\n        \"interaction\": {\r\n            \"source\": \"web\",\r\n            \"au" +
            "thor\": {\r\n                \"username\": \"johndoe\",\r\n                \"name\": \"John " +
            "Doe\",\r\n                \"id\": 10750902,\r\n                \"avatar\": \"http://a0.twi" +
            "mg.com/profile_images/1111111111/example.jpeg\",\r\n                \"link\": \"http:/" +
            "/twitter.com/johndoe\"\r\n            },\r\n            \"type\": \"twitter\",\r\n         " +
            "   \"created_at\": \"Fri, 17 Aug 2012 14:13:08 +0000\",\r\n            \"content\": \"I l" +
            "ike ice cream!\",\r\n            \"id\": \"1e1e875ab43fa233e074337458bc1dca\",\r\n       " +
            "     \"link\": \"http://twitter.com/johndoe/statuses/111111111111111111\",\r\n        " +
            "    \"geo\": {\r\n                \"latitude\": 42.376104,\r\n                \"longitude" +
            "\": -71.237189\r\n            }\r\n        },\r\n        \"twitter\": {\r\n            \"cre" +
            "ated_at\": \"Fri, 17 Aug 2012 14:13:08 +0000\",\r\n            \"domains\": [\r\n        " +
            "        \"4sq.com\"\r\n            ],\r\n            \"geo\": {\r\n                \"latitu" +
            "de\": 42.376104,\r\n                \"longitude\": -71.237189\r\n            },\r\n      " +
            "      \"id\": \"111111111111111111\",\r\n            \"links\": [\r\n                \"http" +
            "://4sq.com/NLM3gD\"\r\n            ],\r\n            \"mentions\": [\r\n                \"" +
            "beyonce\",\r\n                \"ladygaga\"\r\n            ],\r\n            \"place\": {\r\n " +
            "               \"id\": \"90ad0a08b3333d6d\",\r\n                \"url\": \"http://api.twi" +
            "tter.com/1/geo/id/example.json\",\r\n                \"place_type\": \"poi\",\r\n        " +
            "        \"country\": \"United States\",\r\n                \"country_code\": \"US\",\r\n    " +
            "            \"full_name\": \"Cafe On the Common, Waltham\",\r\n                \"name\":" +
            " \"Cafe On the Common\"\r\n            },\r\n            \"source\": \"<a href=\\\"http://e" +
            "xample.com\\\" rel=\\\"nofollow\\\">example</a>\",\r\n            \"text\": \"I like ice cre" +
            "am\",\r\n            \"user\": {\r\n                \"name\": \"John Doe\",\r\n              " +
            "  \"url\": \"http://about.me/John Doe\",\r\n                \"description\": \"all my twe" +
            "ets...\",\r\n                \"location\": \"London\",\r\n                \"statuses_count" +
            "\": 9689,\r\n                \"followers_count\": 2054,\r\n                \"friends_cou" +
            "nt\": 2016,\r\n                \"screen_name\": \"johndoe\",\r\n                \"lang\": \"" +
            "en\",\r\n                \"time_zone\": \"Eastern Time (US & Canada)\",\r\n              " +
            "  \"utc_offset\": -18000,\r\n                \"listed_count\": 118,\r\n                \"" +
            "id\": 11111111,\r\n                \"id_str\": \"11111111\",\r\n                \"geo_enab" +
            "led\": true,\r\n                \"created_at\": \"Fri, 30 Nov 2007 21:26:38 +0000\"\r\n  " +
            "          }\r\n        }\r\n    },\r\n    {\r\n        \"demographic\": {\r\n            \"ge" +
            "nder\": \"mostly_male\"\r\n        },\r\n        \"interaction\": {\r\n            \"source\"" +
            ": \"web\",\r\n            \"author\": {\r\n                \"username\": \"JohnDoe\",\r\n     " +
            "           \"name\": \"John Doe\",\r\n                \"id\": 11111111,\r\n               " +
            " \"avatar\": \"http://a0.twimg.com/profile_images/1111111111/example.jpg\",\r\n       " +
            "         \"link\": \"http://twitter.com/JohnDoe\"\r\n            },\r\n            \"type" +
            "\": \"twitter\",\r\n            \"created_at\": \"Fri, 17 Aug 2012 14:13:09 +0000\",\r\n   " +
            "         \"content\": \"I love ice cream!\",\r\n            \"id\": \"1a1a1a1a1a1a1a1a1a1" +
            "a1a1a1a1a1a1a\",\r\n            \"link\": \"http://twitter.com/JohnDoe/statuses/111111" +
            "111111111111\",\r\n            \"geo\": {\r\n                \"latitude\": 41.48454863,\r\n" +
            "                \"longitude\": -72.79693173\r\n            }\r\n        },\r\n        \"t" +
            "witter\": {\r\n            \"created_at\": \"Fri, 17 Aug 2012 14:13:09 +0000\",\r\n      " +
            "      \"domains\": [\r\n                \"4sq.com\"\r\n            ],\r\n            \"geo\"" +
            ": {\r\n                \"latitude\": 41.48454863,\r\n                \"longitude\": -72." +
            "79693173\r\n            },\r\n            \"id\": \"111111111111111111\",\r\n            \"" +
            "links\": [\r\n                \"http://4sq.com/NMH47L\"\r\n            ],\r\n            " +
            "\"place\": {\r\n                \"id\": \"e5ac52573b5f3333\",\r\n                \"url\": \"h" +
            "ttp://api.twitter.com/1/geo/id/1a1a1a1a1a1a1a1a.json\",\r\n                \"place_t" +
            "ype\": \"poi\",\r\n                \"country\": \"United States\",\r\n                \"coun" +
            "try_code\": \"US\",\r\n                \"full_name\": \"Willow Farm\",\r\n                \"" +
            "name\": \"Willow Farm\"\r\n            },\r\n            \"source\": \"<a href=\\\"http://ex" +
            "ample.com\\\" rel=\\\"nofollow\\\">example</a>\",\r\n            \"text\": \"I love ice crea" +
            "m\",\r\n            \"user\": {\r\n                \"name\": \"John Doe\",\r\n               " +
            " \"description\": \"Man of mystery\\n\",\r\n                \"location\": \"Main street\",\r" +
            "\n                \"statuses_count\": 10073,\r\n                \"followers_count\": 44" +
            "4,\r\n                \"friends_count\": 533,\r\n                \"screen_name\": \"John " +
            "Doe\",\r\n                \"lang\": \"en\",\r\n                \"time_zone\": \"Quito\",\r\n   " +
            "             \"utc_offset\": -18000,\r\n                \"listed_count\": 9,\r\n        " +
            "        \"id\": 11111111,\r\n                \"id_str\": \"11111111\",\r\n                " +
            "\"geo_enabled\": true,\r\n                \"created_at\": \"Sun, 26 Apr 2009 23:38:45 +" +
            "0000\"\r\n            }\r\n        }\r\n    }\r\n]")]
        public string PullJsonArrayFormat {
            get {
                return ((string)(this["PullJsonArrayFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{ \"interaction\": { \"source\": \"web\", \"author\": { \"username\": \"johndoe\", \"name\": \"J" +
            "ohn Doe\", \"id\": 10750902, \"avatar\": \"http://a0.twimg.com/profile_images/11111111" +
            "11/example.jpeg\", \"link\": \"http://twitter.com/johndoe\" }, \"type\": \"twitter\", \"cr" +
            "eated_at\": \"Fri, 17 Aug 2012 14:13:08 +0000\", \"content\": \"I like ice cream!\", \"i" +
            "d\": \"1e1e875ab43fa233e074337458bc1dca\", \"link\": \"http://twitter.com/johndoe/stat" +
            "uses/111111111111111111\", \"geo\": { \"latitude\": 42.376104, \"longitude\": -71.23718" +
            "9 } }, \"twitter\": { \"created_at\": \"Fri, 17 Aug 2012 14:13:08 +0000\", \"domains\": " +
            "[ \"4sq.com\" ], \"geo\": { \"latitude\": 42.376104, \"longitude\": -71.237189 }, \"id\": " +
            "\"111111111111111111\", \"links\": [ \"http://4sq.com/NLM3gD\" ], \"mentions\": [ \"beyon" +
            "ce\", \"ladygaga\" ], \"place\": { \"id\": \"90ad0a08b3333d6d\", \"url\": \"http://api.twitt" +
            "er.com/1/geo/id/example.json\", \"place_type\": \"poi\", \"country\": \"United States\", " +
            "\"country_code\": \"US\", \"full_name\": \"Cafe On the Common, Waltham\", \"name\": \"Cafe " +
            "On the Common\" }, \"source\": \"<a href=\\\"http://example.com\\\" rel=\\\"nofollow\\\">exa" +
            "mple</a>\", \"text\": \"I like ice cream\", \"user\": { \"name\": \"John Doe\", \"url\": \"htt" +
            "p://about.me/John Doe\", \"description\": \"all my tweets...\", \"location\": \"London\"," +
            " \"statuses_count\": 9689, \"followers_count\": 2054, \"friends_count\": 2016, \"screen" +
            "_name\": \"johndoe\", \"lang\": \"en\", \"time_zone\": \"Eastern Time (US & Canada)\", \"utc" +
            "_offset\": -18000, \"listed_count\": 118, \"id\": 11111111, \"id_str\": \"11111111\", \"ge" +
            "o_enabled\": true, \"created_at\": \"Fri, 30 Nov 2007 21:26:38 +0000\" } } }\r\n{ \"demo" +
            "graphic\": { \"gender\": \"mostly_male\" }, \"interaction\": { \"source\": \"web\", \"author" +
            "\": { \"username\": \"JohnDoe\", \"name\": \"John Doe\", \"id\": 11111111, \"avatar\": \"http:" +
            "//a0.twimg.com/profile_images/1111111111/example.jpg\", \"link\": \"http://twitter.c" +
            "om/JohnDoe\" }, \"type\": \"twitter\", \"created_at\": \"Fri, 17 Aug 2012 14:13:09 +0000" +
            "\", \"content\": \"I love ice cream!\", \"id\": \"1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a\", \"li" +
            "nk\": \"http://twitter.com/JohnDoe/statuses/111111111111111111\", \"geo\": { \"latitud" +
            "e\": 41.48454863, \"longitude\": -72.79693173 } }, \"twitter\": { \"created_at\": \"Fri," +
            " 17 Aug 2012 14:13:09 +0000\", \"domains\": [ \"4sq.com\" ], \"geo\": { \"latitude\": 41." +
            "48454863, \"longitude\": -72.79693173 }, \"id\": \"111111111111111111\", \"links\": [ \"h" +
            "ttp://4sq.com/NMH47L\" ], \"place\": { \"id\": \"e5ac52573b5f3333\", \"url\": \"http://api" +
            ".twitter.com/1/geo/id/1a1a1a1a1a1a1a1a.json\", \"place_type\": \"poi\", \"country\": \"U" +
            "nited States\", \"country_code\": \"US\", \"full_name\": \"Willow Farm\", \"name\": \"Willow" +
            " Farm\" }, \"source\": \"<a href=\\\"http://example.com\\\" rel=\\\"nofollow\\\">example</a>" +
            "\", \"text\": \"I love ice cream\", \"user\": { \"name\": \"John Doe\", \"description\": \"Man" +
            " of mystery\\n\", \"location\": \"Main street\", \"statuses_count\": 10073, \"followers_c" +
            "ount\": 444, \"friends_count\": 533, \"screen_name\": \"John Doe\", \"lang\": \"en\", \"time" +
            "_zone\": \"Quito\", \"utc_offset\": -18000, \"listed_count\": 9, \"id\": 11111111, \"id_st" +
            "r\": \"11111111\", \"geo_enabled\": true, \"created_at\": \"Sun, 26 Apr 2009 23:38:45 +0" +
            "000\" } } }")]
        public string PullJsonNewLineFormat {
            get {
                return ((string)(this["PullJsonNewLineFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
    ""id"": ""8d38093ce3a78fbbba6f"",
    ""progress"": 5,
    ""status"": ""running"",
    ""feeds"": ""twitter"",
    ""sample"": 1,
    ""end"": 1359936000,
    ""created_at"": 1362409489,
    ""start"": 1359849600,
    ""user"": ""12919"",
    ""parameters"": ""interaction.content,wordCount,10"",
    ""hash"": ""93558e17de15072fa126370c37c5bd8f""
}")]
        public string HistoricsPreviewRunning {
            get {
                return ((string)(this["HistoricsPreviewRunning"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\r\n    \"id\": \"c59ce40e865f1704b233\",\r\n    \"progress\": 100,\r\n    \"status\": \"succee" +
            "ded\",\r\n    \"feeds\": \"twitter\",\r\n    \"sample\": 1,\r\n    \"end\": 1359936000,\r\n    \"c" +
            "reated_at\": 1362500299,\r\n    \"start\": 1359849600,\r\n    \"user\": \"12919\",\r\n    \"pa" +
            "rameters\": \"interaction.author.link,targetVol,hour;twitter.user.lang,freqDist,10" +
            ";twitter.user.followers_count,numStats,hour;interaction.content,wordCount,10\",\r\n" +
            "    \"hash\": \"93558e17de15072fa126370c37c5bd8f\",\r\n    \"data\": [\r\n        {\r\n     " +
            "       \"target\": \"interaction.author.link\",\r\n            \"analysis\": \"targetVol\"" +
            ",\r\n            \"output\": {\r\n                \"2013/02/03 21:00:00\": 483,\r\n       " +
            "         \"2013/02/03 20:00:00\": 455,\r\n                \"2013/02/03 16:00:00\": 371" +
            ",\r\n                \"2013/02/03 07:00:00\": 212,\r\n                \"2013/02/03 23:0" +
            "0:00\": 3727,\r\n                \"2013/02/03 14:00:00\": 272,\r\n                \"2013" +
            "/02/03 19:00:00\": 453,\r\n                \"2013/02/03 13:00:00\": 218,\r\n           " +
            "     \"2013/02/03 15:00:00\": 328,\r\n                \"2013/02/03 08:00:00\": 181,\r\n " +
            "               \"2013/02/03 11:00:00\": 149,\r\n                \"2013/02/03 10:00:00" +
            "\": 158,\r\n                \"2013/02/03 12:00:00\": 183,\r\n                \"2013/02/0" +
            "3 09:00:00\": 162,\r\n                \"2013/02/03 22:00:00\": 543,\r\n                " +
            "\"2013/02/03 18:00:00\": 437,\r\n                \"2013/02/03 06:00:00\": 261,\r\n      " +
            "          \"2013/02/03 17:00:00\": 396\r\n            },\r\n            \"interval\": \"h" +
            "our\"\r\n        },\r\n        {\r\n            \"target\": \"twitter.user.lang\",\r\n       " +
            "     \"analysis\": \"freqDist\",\r\n            \"output\": {\r\n                \"fr\": 30," +
            "\r\n                \"pt\": 37,\r\n                \"it\": 7,\r\n                \"nl\": 10," +
            "\r\n                \"de\": 12,\r\n                \"ru\": 8,\r\n                \"id\": 26," +
            "\r\n                \"en\": 5450,\r\n                \"es\": 544,\r\n                \"ja\":" +
            " 8\r\n            },\r\n            \"threshold\": 10\r\n        },\r\n        {\r\n        " +
            "    \"target\": \"twitter.user.followers_count\",\r\n            \"analysis\": \"numStats" +
            "\",\r\n            \"output\": {\r\n                \"2013/02/03 21:00:00\": {\r\n         " +
            "           \"min\": 1,\r\n                    \"max\": 50239,\r\n                    \"co" +
            "unt\": 287,\r\n                    \"sum\": 267468\r\n                },\r\n             " +
            "   \"2013/02/03 20:00:00\": {\r\n                    \"min\": 1,\r\n                    " +
            "\"max\": 115771,\r\n                    \"count\": 264,\r\n                    \"sum\": 46" +
            "2205\r\n                },\r\n                \"2013/02/03 16:00:00\": {\r\n            " +
            "        \"min\": 1,\r\n                    \"max\": 24212,\r\n                    \"count" +
            "\": 258,\r\n                    \"sum\": 217525\r\n                },\r\n                " +
            "\"2013/02/03 07:00:00\": {\r\n                    \"min\": 1,\r\n                    \"ma" +
            "x\": 7295,\r\n                    \"count\": 158,\r\n                    \"sum\": 76463\r\n" +
            "                },\r\n                \"2013/02/03 23:00:00\": {\r\n                  " +
            "  \"min\": 1,\r\n                    \"max\": 3017366,\r\n                    \"count\": 2" +
            "458,\r\n                    \"sum\": 6667940\r\n                },\r\n                \"2" +
            "013/02/03 14:00:00\": {\r\n                    \"min\": 1,\r\n                    \"max\"" +
            ": 84525,\r\n                    \"count\": 192,\r\n                    \"sum\": 238159\r\n" +
            "                },\r\n                \"2013/02/03 19:00:00\": {\r\n                  " +
            "  \"min\": 1,\r\n                    \"max\": 4299615,\r\n                    \"count\": 2" +
            "90,\r\n                    \"sum\": 4621461\r\n                },\r\n                \"20" +
            "13/02/03 13:00:00\": {\r\n                    \"min\": 1,\r\n                    \"max\":" +
            " 1002323,\r\n                    \"count\": 168,\r\n                    \"sum\": 1410864" +
            "\r\n                },\r\n                \"2013/02/03 15:00:00\": {\r\n                " +
            "    \"min\": 1,\r\n                    \"max\": 4299885,\r\n                    \"count\":" +
            " 250,\r\n                    \"sum\": 8931897\r\n                },\r\n                \"" +
            "2013/02/03 08:00:00\": {\r\n                    \"min\": 1,\r\n                    \"max" +
            "\": 667865,\r\n                    \"count\": 128,\r\n                    \"sum\": 929846" +
            "\r\n                },\r\n                \"2013/02/03 11:00:00\": {\r\n                " +
            "    \"min\": 1,\r\n                    \"max\": 15981,\r\n                    \"count\": 1" +
            "18,\r\n                    \"sum\": 90075\r\n                },\r\n                \"2013" +
            "/02/03 10:00:00\": {\r\n                    \"min\": 1,\r\n                    \"max\": 1" +
            "46451,\r\n                    \"count\": 119,\r\n                    \"sum\": 227252\r\n  " +
            "              },\r\n                \"2013/02/03 12:00:00\": {\r\n                    " +
            "\"min\": 1,\r\n                    \"max\": 102826,\r\n                    \"count\": 131," +
            "\r\n                    \"sum\": 296061\r\n                },\r\n                \"2013/0" +
            "2/03 09:00:00\": {\r\n                    \"min\": 1,\r\n                    \"max\": 146" +
            "454,\r\n                    \"count\": 125,\r\n                    \"sum\": 365938\r\n    " +
            "            },\r\n                \"2013/02/03 22:00:00\": {\r\n                    \"m" +
            "in\": 1,\r\n                    \"max\": 52317,\r\n                    \"count\": 350,\r\n " +
            "                   \"sum\": 329469\r\n                },\r\n                \"2013/02/0" +
            "3 18:00:00\": {\r\n                    \"min\": 1,\r\n                    \"max\": 429965" +
            "3,\r\n                    \"count\": 292,\r\n                    \"sum\": 5310219\r\n     " +
            "           },\r\n                \"2013/02/03 06:00:00\": {\r\n                    \"mi" +
            "n\": 1,\r\n                    \"max\": 34646,\r\n                    \"count\": 196,\r\n  " +
            "                  \"sum\": 196230\r\n                },\r\n                \"2013/02/03" +
            " 17:00:00\": {\r\n                    \"min\": 1,\r\n                    \"max\": 198732," +
            "\r\n                    \"count\": 270,\r\n                    \"sum\": 437504\r\n        " +
            "        }\r\n            },\r\n            \"interval\": \"hour\"\r\n        },\r\n        {" +
            "\r\n            \"target\": \"interaction.content\",\r\n            \"analysis\": \"wordCou" +
            "nt\",\r\n            \"output\": {\r\n                \"blackberry\": 561,\r\n             " +
            "   \"super\": 433,\r\n                \"disney\": 1009,\r\n                \"audi\": 352,\r" +
            "\n                \"commercial\": 1670,\r\n                \"doritos\": 763,\r\n         " +
            "       \"godaddy\": 439,\r\n                \"taylor\": 603,\r\n                \"bowl\": " +
            "421,\r\n                \"swift\": 592\r\n            },\r\n            \"threshold\": 10\r" +
            "\n        }\r\n    ]\r\n}")]
        public string HistoricsPreviewFinished {
            get {
                return ((string)(this["HistoricsPreviewFinished"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\r\n    \"id\": \"3ddb72ca02389dbf3b46\",\r\n    \"created_at\": 1364303060\r\n}")]
        public string HistoricsPreviewCreate {
            get {
                return ((string)(this["HistoricsPreviewCreate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\r\n    \"count\": 2,\r\n    \"page\": 1,\r\n    \"pages\": 1,\r\n    \"per_page\": 20,\r\n    \"so" +
            "urces\": [\r\n        {\r\n            \"name\": \"\",\r\n            \"source_type\": \"faceb" +
            "ook_page\",\r\n            \"status\": \"running\",\r\n            \"parameters\": [],\r\n   " +
            "         \"auth\": [\r\n                {\r\n                    \"identity_id\": \"7b1be" +
            "3a398e646bbb3c7a5cb9717ba45\",\r\n                    \"source_id\": \"49fa6dcb175b4a8" +
            "ca8cbedb8d9015ed0\",\r\n                    \"status\": \"valid\",\r\n                   " +
            " \"parameters\": {\r\n                        \"value\": \"363056350669209|09af1ce9c5d8" +
            "d23147ec4eeb9a33aac2\"\r\n                    },\r\n                    \"expires_at\":" +
            " 1388556000\r\n                }\r\n            ],\r\n            \"resources\": [\r\n    " +
            "            {\r\n                    \"resource_id\": \"30bc448896de44b88604ac223cb7f" +
            "26f\",\r\n                    \"source_id\": \"49fa6dcb175b4a8ca8cbedb8d9015ed0\",\r\n   " +
            "                 \"status\": \"valid\",\r\n                    \"parameters\": {\r\n      " +
            "                  \"url\": \"http://www.facebook.com/theguardian\",\r\n               " +
            "         \"title\": \"The Guardian\",\r\n                        \"id\": 10513336322\r\n  " +
            "                  }\r\n                },\r\n                {\r\n                    " +
            "\"resource_id\": \"d43024171340458fb6f124967fd126c1\",\r\n                    \"source_" +
            "id\": \"49fa6dcb175b4a8ca8cbedb8d9015ed0\",\r\n                    \"status\": \"valid\"," +
            "\r\n                    \"parameters\": {\r\n                        \"url\": \"http://ww" +
            "w.giffgaff.com\",\r\n                        \"title\": \"giffgaffmobile\",\r\n          " +
            "              \"id\": 287613300716\r\n                    }\r\n                }\r\n    " +
            "        ],\r\n            \"created_at\": 1370266044,\r\n            \"id\": \"48fa6dcb17" +
            "5b4a8ca8cbedb8d9015ed0\"\r\n        },\r\n        {\r\n            \"name\": \"\",\r\n       " +
            "     \"source_type\": \"facebook_page\",\r\n            \"status\": \"running\",\r\n        " +
            "    \"parameters\": [],\r\n            \"auth\": [\r\n                {\r\n               " +
            "     \"identity_id\": \"0047a9e7f4bb4931b65e7e9bd299ddd1\",\r\n                    \"so" +
            "urce_id\": \"fd2e72e3a7ae40c2a6e86e96381d8165\",\r\n                    \"status\": \"va" +
            "lid\",\r\n                    \"parameters\": {\r\n                        \"value\": \"36" +
            "3056350669209|09af1ce9c5d8d23147ec4eeb9a33aac2\"\r\n                    },\r\n       " +
            "             \"expires_at\": 1388556000\r\n                }\r\n            ],\r\n      " +
            "      \"resources\": [\r\n                {\r\n                    \"resource_id\": \"d65" +
            "90d550db94266af6f53884dd65ca4\",\r\n                    \"source_id\": \"fd2e72e3a7ae4" +
            "0c2a6e86e96381d8165\",\r\n                    \"status\": \"valid\",\r\n                 " +
            "   \"parameters\": {\r\n                        \"url\": \"http://www.facebook.com/ther" +
            "ollingstones\",\r\n                        \"title\": \"The Rolling Stones\",\r\n        " +
            "                \"id\": 8305888286\r\n                    }\r\n                }\r\n    " +
            "        ],\r\n            \"created_at\": 1370266045,\r\n            \"id\": \"fa2e72e3a7" +
            "ae40c2a6e86e96381d8165\"\r\n        }\r\n    ]\r\n}")]
        public string SourceGet {
            get {
                return ((string)(this["SourceGet"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
    ""name"": """",
    ""source_type"": ""facebook_page"",
    ""status"": ""running"",
    ""parameters"": [],
    ""auth"": [
        {
            ""identity_id"": ""0047a9e7f4bb4931b65e7e9bd299ddd1"",
            ""source_id"": ""fd2e72e3a7ae40c2a6e86e96381d8165"",
            ""status"": ""valid"",
            ""parameters"": {
                ""value"": ""363056350669209|09af1ce9c5d8d23147ec4eeb9a33aac2""
            },
            ""expires_at"": 1388556000
        }
    ],
    ""resources"": [
        {
            ""resource_id"": ""d6590d550db94266af6f53884dd65ca4"",
            ""source_id"": ""fd2e72e3a7ae40c2a6e86e96381d8165"",
            ""status"": ""valid"",
            ""parameters"": {
                ""url"": ""http://www.facebook.com/therollingstones"",
                ""title"": ""The Rolling Stones"",
                ""id"": 8305888286
            }
        }
    ],
    ""created_at"": 1370266044,
    ""id"": ""fa2e72e3a7ae40c2a6e86e96381d8165""
}")]
        public string SourceGetById {
            get {
                return ((string)(this["SourceGetById"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\r\n    \"count\": 2,\r\n    \"page\": 1,\r\n    \"pages\": 2,\r\n    \"per_page\": 1,\r\n    \"sou" +
            "rces\": [\r\n        {\r\n            \"name\": \"\",\r\n            \"source_type\": \"facebo" +
            "ok_page\",\r\n            \"status\": \"running\",\r\n            \"parameters\": [],\r\n    " +
            "        \"auth\": [\r\n                {\r\n                    \"identity_id\": \"7b1be3" +
            "a398e646bbb3c7a5cb9717ba45\",\r\n                    \"source_id\": \"49fa6dcb175b4a8c" +
            "a8cbedb8d9015ed0\",\r\n                    \"status\": \"valid\",\r\n                    " +
            "\"parameters\": {\r\n                        \"value\": \"363056350669209|09af1ce9c5d8d" +
            "23147ec4eeb9a33aac2\"\r\n                    },\r\n                    \"expires_at\": " +
            "1388556000\r\n                }\r\n            ],\r\n            \"resources\": [\r\n     " +
            "           {\r\n                    \"resource_id\": \"30bc448896de44b88604ac223cb7f2" +
            "6f\",\r\n                    \"source_id\": \"49fa6dcb175b4a8ca8cbedb8d9015ed0\",\r\n    " +
            "                \"status\": \"valid\",\r\n                    \"parameters\": {\r\n       " +
            "                 \"url\": \"http://www.facebook.com/theguardian\",\r\n                " +
            "        \"title\": \"The Guardian\",\r\n                        \"id\": 10513336322\r\n   " +
            "                 }\r\n                },\r\n                {\r\n                    \"" +
            "resource_id\": \"d43024171340458fb6f124967fd126c1\",\r\n                    \"source_i" +
            "d\": \"49fa6dcb175b4a8ca8cbedb8d9015ed0\",\r\n                    \"status\": \"valid\",\r" +
            "\n                    \"parameters\": {\r\n                        \"url\": \"http://www" +
            ".giffgaff.com\",\r\n                        \"title\": \"giffgaffmobile\",\r\n           " +
            "             \"id\": 287613300716\r\n                    }\r\n                }\r\n     " +
            "       ],\r\n            \"created_at\": 1370266044,\r\n            \"id\": \"48fa6dcb175" +
            "b4a8ca8cbedb8d9015ed0\"\r\n        }\r\n    ]\r\n}")]
        public string SourceGetPage {
            get {
                return ((string)(this["SourceGetPage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
  ""id"": ""da4f8df71a0f43698acf9240b5ad668f"",
  ""name"": ""news_source"",
  ""source_type"": ""facebook_page"",
  ""created_at"": 1391707662,
  ""status"": ""stopped"",
  ""parameters"": {
    ""posts_by_others"": false,
    ""likes"": true,
    ""comments"": true
  },
  ""resources"": [
    {
      ""parameters"": {
        ""title"": ""The Guardian"",
        ""url"": ""http://www.facebook.com/theguardian"",
        ""id"": ""10513336322""
      },
      ""resource_id"": ""7e8099d7f34f466e8bee01852243e16b""
    }
  ],
  ""auth"": [
    {
      ""expires_at"": 2112112110,
      ""parameters"": {
        ""value"": ""EZBXlFZBUgBYmjHkxc2pPmzLeJJYmAvQkwZCRdm0A1NAjidHy1h""
      },
      ""identity_id"": ""d38e5598142746e19689ddee65ddca55""
    }
  ]
}")]
        public string SourceCreate {
            get {
                return ((string)(this["SourceCreate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
    ""name"": """",
    ""source_type_id"": ""facebook_page"",
    ""status"": ""active"",
    ""parameters"": [],
    ""identities"": [
        {
            ""identity_id"": ""0047a9e7f4bb4931b65e7e9bd299ddd1"",
            ""source_id"": ""fd2e72e3a7ae40c2a6e86e96381d8165"",
            ""status"": ""valid"",
            ""parameters"": {
                ""value"": ""363056350669209|09af1ce9c5d8d23147ec4eeb9a33aac2""
            },
            ""expires_at"": 1388556000
        }
    ],
    ""resources"": [
        {
            ""resource_id"": ""d6590d550db94266af6f53884dd65ca4"",
            ""source_id"": ""fd2e72e3a7ae40c2a6e86e96381d8165"",
            ""status"": ""valid"",
            ""parameters"": {
                ""url"": ""http://www.facebook.com/therollingstones"",
                ""title"": ""The Rolling Stones"",
                ""id"": 8305888286
            }
        }
    ],
    ""id"": ""fa2e72e3a7ae40c2a6e86e96381d8165""
}")]
        public string SourceStart {
            get {
                return ((string)(this["SourceStart"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
    ""name"": """",
    ""source_type_id"": ""facebook_page"",
    ""status"": ""paused"",
    ""parameters"": [],
    ""identities"": [
        {
            ""identity_id"": ""0047a9e7f4bb4931b65e7e9bd299ddd1"",
            ""source_id"": ""fd2e72e3a7ae40c2a6e86e96381d8165"",
            ""status"": ""valid"",
            ""parameters"": {
                ""value"": ""363056350669209|09af1ce9c5d8d23147ec4eeb9a33aac2""
            },
            ""expires_at"": 1388556000
        }
    ],
    ""resources"": [
        {
            ""resource_id"": ""d6590d550db94266af6f53884dd65ca4"",
            ""source_id"": ""fd2e72e3a7ae40c2a6e86e96381d8165"",
            ""status"": ""valid"",
            ""parameters"": {
                ""url"": ""http://www.facebook.com/therollingstones"",
                ""title"": ""The Rolling Stones"",
                ""id"": 8305888286
            }
        }
    ],
    ""id"": ""fa2e72e3a7ae40c2a6e86e96381d8165""
}")]
        public string SourceStop {
            get {
                return ((string)(this["SourceStop"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
  ""id"": ""da4f8df71a0f43698acf9240b5ad668f"",
  ""name"": ""news_source"",
  ""source_type"": ""facebook_page"",
  ""created_at"": 1391707662,
  ""status"": ""running"",
  ""parameters"": {
    ""posts_by_others"": true,
    ""likes"": false,
    ""comments"": false
  },
  ""resources"": [
    {
      ""parameters"": {
        ""title"": ""The Guardian"",
        ""url"": ""http://www.facebook.com/theguardian"",
        ""id"": ""10513336322""
      },
      ""resource_id"": ""7e8099d7f34f466e8bee01852243e16b""
    }
  ],
  ""auth"": [
    {
      ""expires_at"": 2112112110,
      ""parameters"": {
        ""value"": ""EZBXlFZBUgBYmjHkxc2pPmzLeJJYmAvQkwZCRdm0A1NAjidHy1h""
      },
      ""identity_id"": ""d38e5598142746e19689ddee65ddca55""
    }
  ]
}")]
        public string SourceUpdate {
            get {
                return ((string)(this["SourceUpdate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
    ""count"": 20,
    ""page"": 1,
    ""pages"": 1,
    ""per_page"": 20,
    ""log_entries"": [
        {
            ""id"": 835176,
            ""event_time"": 1372133607,
            ""success"": false,
            ""message"": ""OAuthException(4): (#4) Application request limit reached""
        },
        {
            ""id"": 835158,
            ""event_time"": 1372133599,
            ""success"": false,
            ""message"": ""OAuthException(4): (#4) Application request limit reached""
        }
    ]
}")]
        public string SourceLog {
            get {
                return ((string)(this["SourceLog"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
    ""count"": 20,
    ""page"": 1,
    ""pages"": 20,
    ""per_page"": 1,
    ""log_entries"": [
        {
            ""id"": 835176,
            ""event_time"": 1372133607,
            ""success"": false,
            ""message"": ""OAuthException(4): (#4) Application request limit reached""
        }
    ]
}")]
        public string SourceLogPage {
            get {
                return ((string)(this["SourceLogPage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
  ""id"": ""da4f8df71a0f43698acf9240b5ad668f"",
  ""name"": ""news_source"",
  ""source_type"": ""facebook_page"",
  ""created_at"": 1391707662,
  ""status"": ""stopped"",
  ""parameters"": {
    ""posts_by_others"": false,
    ""likes"": true,
    ""comments"": true
  },
  ""resources"": [
    {
      ""parameters"": {
        ""title"": ""The Guardian"",
        ""url"": ""http://www.facebook.com/theguardian"",
        ""id"": ""10513336322""
      },
      ""resource_id"": ""7e8099d7f34f466e8bee01852243e16b""
    },
    {
      ""parameters"": {
        ""title"": ""The Sun"",
        ""url"": ""http://www.facebook.com/thesun"",
        ""id"": ""161385360554578""
      },
      ""resource_id"": ""b801b1f3a6934cf29e02d092bff9b7f1""
    }
  ],
  ""auth"": [
    {
      ""expires_at"": 2112112110,
      ""parameters"": {
        ""value"": ""EZBXlFZBUgBYmjHkxc2pPmzLeJJYmAvQkwZCRdm0A1NAjidHy1h""
      },
      ""identity_id"": ""d38e5598142746e19689ddee65ddca55""
    }
  ]
}")]
        public string SourceResourceAdd {
            get {
                return ((string)(this["SourceResourceAdd"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
  ""id"": ""da4f8df71a0f43698acf9240b5ad668f"",
  ""name"": ""news_source"",
  ""source_type"": ""facebook_page"",
  ""created_at"": 1391707662,
  ""status"": ""stopped"",
  ""parameters"": {
    ""posts_by_others"": false,
    ""likes"": true,
    ""comments"": true
  },
  ""resources"": [
    {
      ""parameters"": {
        ""title"": ""The Guardian"",
        ""url"": ""http://www.facebook.com/theguardian"",
        ""id"": ""10513336322""
      },
      ""resource_id"": ""7e8099d7f34f466e8bee01852243e16b""
    }
  ],
  ""auth"": [
    {
      ""expires_at"": 2112112110,
      ""parameters"": {
        ""value"": ""EZBXlFZBUgBYmjHkxc2pPmzLeJJYmAvQkwZCRdm0A1NAjidHy1h""
      },
      ""identity_id"": ""d38e5598142746e19689ddee65ddca55""
    }
  ]
}")]
        public string SourceResourceRemove {
            get {
                return ((string)(this["SourceResourceRemove"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
  ""id"": ""da4f8df71a0f43698acf9240b5ad668f"",
  ""name"": ""news_source"",
  ""source_type"": ""facebook_page"",
  ""created_at"": 1391707662,
  ""status"": ""running"",
  ""parameters"": {
    ""posts_by_others"": true,
    ""likes"": false,
    ""comments"": false
  },
  ""resources"": [
    {
      ""parameters"": {
        ""title"": ""The Guardian"",
        ""url"": ""http://www.facebook.com/theguardian"",
        ""id"": ""10513336322""
      },
      ""resource_id"": ""7e8099d7f34f466e8bee01852243e16b""
    }
  ],
  ""auth"": [
    {
      ""expires_at"": 2112112110,
      ""parameters"": {
        ""value"": ""EZBXlFZBUgBYmjHkxc2pPmzLeJJYmAvQkwZCRdm0A1NAjidHy1h""
      },
      ""identity_id"": ""d38e5598142746e19689ddee65ddca55""
    },
    {
      ""expires_at"": 2112112110,
      ""parameters"": {
        ""value"": ""AZBXlFZBUgBYmjHkxc2pPmzLeJJYmAvQkwZCRdm0A1NAjidHy1h""
      },
      ""identity_id"": ""c801b1f3a6934cf29e02d092bff9b7f1""
    }
  ]
}")]
        public string SourceAuthAdd {
            get {
                return ((string)(this["SourceAuthAdd"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
  ""id"": ""da4f8df71a0f43698acf9240b5ad668f"",
  ""name"": ""news_source"",
  ""source_type"": ""facebook_page"",
  ""created_at"": 1391707662,
  ""status"": ""running"",
  ""parameters"": {
    ""posts_by_others"": true,
    ""likes"": false,
    ""comments"": false
  },
  ""resources"": [
    {
      ""parameters"": {
        ""title"": ""The Guardian"",
        ""url"": ""http://www.facebook.com/theguardian"",
        ""id"": ""10513336322""
      },
      ""resource_id"": ""7e8099d7f34f466e8bee01852243e16b""
    }
  ],
  ""auth"": [
    {
      ""expires_at"": 2112112110,
      ""parameters"": {
        ""value"": ""EZBXlFZBUgBYmjHkxc2pPmzLeJJYmAvQkwZCRdm0A1NAjidHy1h""
      },
      ""identity_id"": ""d38e5598142746e19689ddee65ddca55""
    }
  ]
}")]
        public string SourceAuthRemove {
            get {
                return ((string)(this["SourceAuthRemove"]));
            }
        }
    }
}
