//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSiftTests {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class PylonAPIResponses : global::System.Configuration.ApplicationSettingsBase {
        
        private static PylonAPIResponses defaultInstance = ((PylonAPIResponses)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PylonAPIResponses())));
        
        public static PylonAPIResponses Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\r\n    \"count\": 15,\r\n    \"page\": 1,\r\n    \"pages\": 1,\r\n    \"per_page\": 25,\r\n    \"s" +
            "ubscriptions\": [\r\n        {\r\n            \"id\": \"12231f2f3825fe4c79e4f5def24c41fa" +
            "8914f198\",\r\n            \"volume\": 0,\r\n            \"start\": 1453482165,\r\n        " +
            "    \"end\": 1453482171,\r\n            \"status\": \"stopped\",\r\n            \"name\": \"E" +
            "xample recording\",\r\n            \"reached_capacity\": false,\r\n            \"identit" +
            "y_id\": \"eb3fd831cb9f1441beeae6c09b5af15f\",\r\n            \"hash\": \"226dd0ad87e911b" +
            "b72c3f6ee4750247b\",\r\n            \"remaining_index_capacity\": 1000000,\r\n         " +
            "   \"remaining_account_capacity\": 1000000\r\n        },\r\n        {\r\n            \"id" +
            "\": \"de78f132b8b5821f3b7c5cc3beb2a82d2856e3cb\",\r\n            \"volume\": 0,\r\n      " +
            "      \"start\": 1453482205,\r\n            \"end\": 1453482821,\r\n            \"status\"" +
            ": \"stopped\",\r\n            \"name\": \"Example recording\",\r\n            \"reached_cap" +
            "acity\": false,\r\n            \"identity_id\": \"eb3fd831cb9f1441beeae6c09b5af15f\",\r\n" +
            "            \"hash\": \"226dd0ad87e911bb72c3f6ee4750247b\",\r\n            \"remaining_" +
            "index_capacity\": 1000000,\r\n            \"remaining_account_capacity\": 1000000\r\n  " +
            "      },\r\n        {\r\n            \"id\": \"5a43a2a8e8d281267535e64ca957826cfaabd821" +
            "\",\r\n            \"volume\": 0,\r\n            \"start\": 1453481852,\r\n            \"end" +
            "\": 1453482122,\r\n            \"status\": \"stopped\",\r\n            \"name\": \"Example r" +
            "ecording\",\r\n            \"reached_capacity\": false,\r\n            \"identity_id\": \"" +
            "eb3fd831cb9f1441beeae6c09b5af15f\",\r\n            \"hash\": \"226dd0ad87e911bb72c3f6e" +
            "e4750247b\",\r\n            \"remaining_index_capacity\": 1000000,\r\n            \"rema" +
            "ining_account_capacity\": 1000000\r\n        }\r\n    ]\r\n}")]
        public string Get {
            get {
                return ((string)(this["Get"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"created_at\":\"1417191702\"}")]
        public string Validate {
            get {
                return ((string)(this["Validate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"hash\":\"58eb8c4b74257406547ab1ed3be346a8\",\"created_at\":\"1417428264\"}")]
        public string Compile {
            get {
                return ((string)(this["Compile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
    ""id"": ""12231f2f3825fe4c79e4f5def24c41fa8914f198"",
    ""volume"": 0,
    ""start"": 1453482165,
    ""end"": 1453482171,
    ""status"": ""stopped"",
    ""name"": ""Example recording"",
    ""reached_capacity"": false,
    ""identity_id"": ""eb3fd831cb9f1441beeae6c09b5af15f"",
    ""hash"": ""226dd0ad87e911bb72c3f6ee4750247b"",
    ""remaining_index_capacity"": 1000000,
    ""remaining_account_capacity"": 1000000
}")]
        public string GetOne {
            get {
                return ((string)(this["GetOne"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"interactions\":0,\"unique_authors\":0,\"analysis\":{\"analysis_type\":\"freqDist\",\"para" +
            "meters\":{\"threshold\":5,\"target\":\"fb.author.age\"},\"results\":[],\"redacted\":false}}" +
            "")]
        public string Analyze {
            get {
                return ((string)(this["Analyze"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[\"tag.one\",\"tag.two\",\"tag.three\"]")]
        public string Tags {
            get {
                return ((string)(this["Tags"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\r\n  \"interactions\": 23400,\r\n  \"unique_authors\": 20000,\r\n  \"analysis\": {\r\n    \"an" +
            "alysis_type\": \"freqDist\",\r\n    \"parameters\": {\r\n      \"target\": \"fb.author.gende" +
            "r\",\r\n      \"threshold\": 3\r\n    },\r\n    \"results\": [\r\n      {\r\n        \"key\": \"ma" +
            "le\",\r\n        \"interactions\": 13400,\r\n        \"unique_authors\": 10000,\r\n        " +
            "\"child\": {\r\n          \"analysis_type\": \"freqDist\",\r\n          \"parameters\": {\r\n " +
            "           \"target\": \"fb.author.age\",\r\n            \"threshold\": 3\r\n          },\r" +
            "\n          \"results\": [\r\n            {\r\n              \"key\": \"25-34\",\r\n         " +
            "     \"interactions\": 13000,\r\n              \"unique_authors\": 9800\r\n            }" +
            "\r\n          ],\r\n          \"redacted\": false\r\n        }\r\n      },\r\n      {\r\n     " +
            "   \"key\": \"female\",\r\n        \"interactions\": 5500,\r\n        \"unique_authors\": 55" +
            "00,\r\n        \"child\": {\r\n          \"analysis_type\": \"freqDist\",\r\n          \"para" +
            "meters\": {\r\n            \"target\": \"fb.author.age\",\r\n            \"threshold\": 3\r\n" +
            "          },\r\n          \"results\": [\r\n            {\r\n              \"key\": \"18-24" +
            "\",\r\n              \"interactions\": 5100,\r\n              \"unique_authors\": 4900\r\n " +
            "           },\r\n            {\r\n              \"key\": \"25-34\",\r\n              \"inte" +
            "ractions\": 300,\r\n              \"unique_authors\": 300\r\n            }\r\n          ]" +
            ",\r\n          \"redacted\": false\r\n        }\r\n      },\r\n      {\r\n        \"key\": \"un" +
            "known\",\r\n        \"interactions\": 4500,\r\n        \"unique_authors\": 4500,\r\n       " +
            " \"child\": {\r\n          \"analysis_type\": \"freqDist\",\r\n          \"parameters\": {\r\n" +
            "            \"target\": \"fb.author.age\",\r\n            \"threshold\": 3\r\n          }," +
            "\r\n          \"results\": [\r\n            {\r\n              \"key\": \"18-24\",\r\n        " +
            "      \"interactions\": 4100,\r\n              \"unique_authors\": 3900\r\n            }" +
            "\r\n          ],\r\n          \"redacted\": false\r\n        }\r\n      }\r\n    ],\r\n    \"re" +
            "dacted\": false\r\n  }\r\n}")]
        public string AnalyzeNested {
            get {
                return ((string)(this["AnalyzeNested"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\r\n   \"interactions\":[\r\n      {\r\n         \"fb\":{\r\n            \"all\":{\r\n          " +
            "     \"content\":\"Ford transit jumbo 125T[REDACTED] very good condition engine and" +
            " gearbox in perfect condition after changing oil and filters very good tires new" +
            " brake pads 171,000 miles mot due 09/03/2016 3 sets of keys engine capacity of 2" +
            ".4 \\n2000Â£ Contact [REDACTED]2\"\r\n            },\r\n            \"language\":\"en\",\r\n" +
            "            \"public\":true,\r\n            \"topic_ids\":[\r\n               2015162332" +
            "90643,\r\n               113122812035593,\r\n               786001198133570\r\n       " +
            "     ],\r\n            \"topics\":[\r\n               {\r\n                  \"category\":" +
            "\"Cars\",\r\n                  \"category_name\":\"Cars|Ford Transit\",\r\n               " +
            "   \"name\":\"Ford Transit\"\r\n               },\r\n               {\r\n                 " +
            " \"category\":\"Interest\",\r\n                  \"category_name\":\"Interest|Transmissio" +
            "n (mechanics)\",\r\n                  \"name\":\"Transmission (mechanics)\"\r\n          " +
            "     }\r\n            ]\r\n         },\r\n         \"interaction\":{\r\n            \"conte" +
            "nt\":\"Ford transit jumbo 125T[REDACTED] very good condition engine and gearbox in" +
            " perfect condition after changing oil and filters very good tires new brake pads" +
            " 171,000 miles mot due 09/03/2016 3 sets of keys engine capacity of 2.4 \\n2000Â£" +
            " Contact [REDACTED]2\",\r\n            \"created_at\":\"Thu, 12 Nov 2015 10:25:49 +000" +
            "0\",\r\n            \"id\":\"0796249ef838d20b92759a2062b2f321\",\r\n            \"subtype\"" +
            ":\"story\",\r\n            \"tag_tree\":{\r\n               \"automotive\":{\r\n            " +
            "      \"brand\":[\r\n                     \"Ford\"\r\n                  ],\r\n            " +
            "      \"feature\":[\r\n                     \"Practicality\",\r\n                     \"S" +
            "afety\",\r\n                     \"Mechanical Specification\"\r\n                  ]\r\n " +
            "              },\r\n               \"non_spam_sale\":0.65654024215803,\r\n            " +
            "   \"other\":-0.077210687626018,\r\n               \"spam\":-0.15882095602098\r\n       " +
            "     }\r\n         }\r\n      }\r\n   ],\r\n   \"remaining\":80,\r\n   \"reset_at\":1447327564" +
            "\r\n}")]
        public string Sample {
            get {
                return ((string)(this["Sample"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\r\n    \"id\": \"f78491987d92bef86e8b0cee5a64b3ab360f059d\"\r\n}")]
        public string Start {
            get {
                return ((string)(this["Start"]));
            }
            set {
                this["Start"] = value;
            }
        }
    }
}
