//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSiftTests.Pylon {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class ReferenceDataAPIResponses : global::System.Configuration.ApplicationSettingsBase {
        
        private static ReferenceDataAPIResponses defaultInstance = ((ReferenceDataAPIResponses)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ReferenceDataAPIResponses())));
        
        public static ReferenceDataAPIResponses Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\r\n    \"count\": 15,\r\n    \"page\": 1,\r\n    \"pages\": 1,\r\n    \"per_page\": 25,\r\n    \"d" +
            "ata\": [\r\n        {\r\n            \"name\": \"User member functions\",\r\n            \"s" +
            "lug\": \"/functions\",\r\n            \"description\": \"\"\r\n        },\r\n        {\r\n     " +
            "       \"name\": \"User member seniorities\",\r\n            \"slug\": \"/seniorities\",\r\n" +
            "            \"description\": \"\"\r\n        },\r\n        {\r\n            \"name\": \"User " +
            "member employer industry sectors\",\r\n            \"slug\": \"/sectors\",\r\n           " +
            " \"description\": \"\"\r\n        },\r\n        {\r\n            \"name\": \"User member empl" +
            "oyer sizes\",\r\n            \"slug\": \"/company_sizes\",\r\n            \"description\": " +
            "\"\"\r\n        },\r\n        {\r\n            \"name\": \"User member field groups names\"," +
            "\r\n            \"slug\": \"/field_names\",\r\n            \"description\": \"\"\r\n        }," +
            "\r\n        {\r\n            \"name\": \"User member degree groups\",\r\n            \"slug" +
            "\": \"/degree_groups\",\r\n            \"description\": \"\"\r\n        },\r\n        {\r\n    " +
            "        \"name\": \"User member country\",\r\n            \"slug\": \"/countries\",\r\n     " +
            "       \"description\": \"\"\r\n        },\r\n        {\r\n            \"name\": \"User membe" +
            "r gender\",\r\n            \"slug\": \"/genders\",\r\n            \"description\": \"\"\r\n    " +
            "    },\r\n        {\r\n            \"name\": \"User member age\",\r\n            \"slug\": \"" +
            "/ages\",\r\n            \"description\": \"\"\r\n        },\r\n        {\r\n            \"name" +
            "\": \"User member minor continent\",\r\n            \"slug\": \"/minor_continents\",\r\n   " +
            "         \"description\": \"\"\r\n        },\r\n        {\r\n            \"name\": \"User mem" +
            "ber field groups\",\r\n            \"slug\": \"/field_groups\",\r\n            \"descripti" +
            "on\": \"\"\r\n        },\r\n        {\r\n            \"name\": \"User member custom segments" +
            "\",\r\n            \"slug\": \"/custom_segments\",\r\n            \"description\": \"\"\r\n    " +
            "    },\r\n        {\r\n            \"name\": \"User member education status\",\r\n        " +
            "    \"slug\": \"/education_statuses\",\r\n            \"description\": \"\"\r\n        },\r\n " +
            "       {\r\n            \"name\": \"User member employer industry sectors\",\r\n        " +
            "    \"slug\": \"/industries\",\r\n            \"description\": \"\"\r\n        },\r\n        {" +
            "\r\n            \"name\": \"List all reference data items\",\r\n            \"slug\": \"/de" +
            "mographic_values\",\r\n            \"description\": \"\"\r\n        }\r\n    ]\r\n}")]
        public string GetAll {
            get {
                return ((string)(this["GetAll"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
    ""count"": 15,
    ""page"": 2,
    ""pages"": 3,
    ""per_page"": 5,
    ""data"": [
        {
            ""name"": ""User member degree groups"",
            ""slug"": ""/degree_groups"",
            ""description"": """"
        },
        {
            ""name"": ""User member country"",
            ""slug"": ""/countries"",
            ""description"": """"
        },
        {
            ""name"": ""User member gender"",
            ""slug"": ""/genders"",
            ""description"": """"
        },
        {
            ""name"": ""User member age"",
            ""slug"": ""/ages"",
            ""description"": """"
        },
        {
            ""name"": ""User member minor continent"",
            ""slug"": ""/minor_continents"",
            ""description"": """"
        }
    ]
}")]
        public string GetAllSmallPage {
            get {
                return ((string)(this["GetAllSmallPage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\r\n    \"count\": 26,\r\n    \"values\": [\r\n        {\r\n            \"value\": \"accounting" +
            "\",\r\n            \"title\": \"Accounting\"\r\n        },\r\n        {\r\n            \"value" +
            "\": \"administrative\",\r\n            \"title\": \"Administrative\"\r\n        },\r\n       " +
            " {\r\n            \"value\": \"arts and design\",\r\n            \"title\": \"Arts and Desi" +
            "gn\"\r\n        },\r\n        {\r\n            \"value\": \"business development\",\r\n      " +
            "      \"title\": \"Business Development\"\r\n        },\r\n        {\r\n            \"value" +
            "\": \"community and social services\",\r\n            \"title\": \"Community and Social " +
            "Services\"\r\n        },\r\n        {\r\n            \"value\": \"consulting\",\r\n          " +
            "  \"title\": \"Consulting\"\r\n        },\r\n        {\r\n            \"value\": \"education\"" +
            ",\r\n            \"title\": \"Education\"\r\n        },\r\n        {\r\n            \"value\":" +
            " \"engineering\",\r\n            \"title\": \"Engineering\"\r\n        },\r\n        {\r\n    " +
            "        \"value\": \"entrepreneurship\",\r\n            \"title\": \"Entrepreneurship\"\r\n " +
            "       },\r\n        {\r\n            \"value\": \"finance\",\r\n            \"title\": \"Fin" +
            "ance\"\r\n        },\r\n        {\r\n            \"value\": \"healthcare services\",\r\n     " +
            "       \"title\": \"Healthcare Services\"\r\n        },\r\n        {\r\n            \"value" +
            "\": \"human resources\",\r\n            \"title\": \"Human Resources\"\r\n        },\r\n     " +
            "   {\r\n            \"value\": \"information technology\",\r\n            \"title\": \"Info" +
            "rmation Technology\"\r\n        },\r\n        {\r\n            \"value\": \"legal\",\r\n     " +
            "       \"title\": \"Legal\"\r\n        },\r\n        {\r\n            \"value\": \"marketing\"" +
            ",\r\n            \"title\": \"Marketing\"\r\n        },\r\n        {\r\n            \"value\":" +
            " \"media and communication\",\r\n            \"title\": \"Media and Communication\"\r\n   " +
            "     },\r\n        {\r\n            \"value\": \"military and protective services\",\r\n  " +
            "          \"title\": \"Military and Protective Services\"\r\n        },\r\n        {\r\n  " +
            "          \"value\": \"operations\",\r\n            \"title\": \"Operations\"\r\n        },\r" +
            "\n        {\r\n            \"value\": \"product management\",\r\n            \"title\": \"Pr" +
            "oduct Management\"\r\n        },\r\n        {\r\n            \"value\": \"program and proj" +
            "ect management\",\r\n            \"title\": \"Program and Project Management\"\r\n       " +
            " },\r\n        {\r\n            \"value\": \"purchasing\",\r\n            \"title\": \"Purcha" +
            "sing\"\r\n        },\r\n        {\r\n            \"value\": \"quality assurance\",\r\n       " +
            "     \"title\": \"Quality Assurance\"\r\n        },\r\n        {\r\n            \"value\": \"" +
            "real estate\",\r\n            \"title\": \"Real Estate\"\r\n        },\r\n        {\r\n      " +
            "      \"value\": \"research\",\r\n            \"title\": \"Research\"\r\n        },\r\n       " +
            " {\r\n            \"value\": \"sales\",\r\n            \"title\": \"Sales\"\r\n        },\r\n   " +
            "     {\r\n            \"value\": \"support\",\r\n            \"title\": \"Support\"\r\n       " +
            " }\r\n    ]\r\n}")]
        public string Functions {
            get {
                return ((string)(this["Functions"]));
            }
        }
    }
}
