//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSiftTests.Pylon {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class TaskAPIResponses : global::System.Configuration.ApplicationSettingsBase {
        
        private static TaskAPIResponses defaultInstance = ((TaskAPIResponses)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new TaskAPIResponses())));
        
        public static TaskAPIResponses Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\r\n    \"count\": 18,\r\n    \"page\": 1,\r\n    \"pages\": 1,\r\n    \"per_page\": 25,\r\n    \"t" +
            "asks\": [\r\n        {\r\n            \"created_at\": 1468879258,\r\n            \"id\": \"6" +
            "763dd472cf7e5af9cf1752627f11710a5335953\",\r\n            \"identity_id\": \"03a78e036" +
            "afb076a6606c5195c1f9b42\",\r\n            \"name\": \"Bens Test\",\r\n            \"parame" +
            "ters\": {\r\n                \"end\": 1468863265,\r\n                \"start\": 146877686" +
            "5\r\n            },\r\n            \"status\": \"Completed\",\r\n            \"subscription" +
            "_id\": \"e9dde04774540ac119c2317a4d15a8b3a1350937\",\r\n            \"type\": \"analysis" +
            "\",\r\n            \"updated_at\": 1468879261\r\n        },\r\n        {\r\n            \"cr" +
            "eated_at\": 1468856049,\r\n            \"id\": \"39ca0d5ad817a4a4b1a1ba5c878639459040f" +
            "428\",\r\n            \"identity_id\": \"03a78e036afb076a6606c5195c1f9b42\",\r\n         " +
            "   \"name\": \"Time series analysis 1\",\r\n            \"parameters\": {\r\n             " +
            "   \"end\": 1468856049,\r\n                \"start\": 1467646449\r\n            },\r\n    " +
            "        \"status\": \"Completed\",\r\n            \"subscription_id\": \"e9dde04774540ac1" +
            "19c2317a4d15a8b3a1350937\",\r\n            \"type\": \"analysis\",\r\n            \"update" +
            "d_at\": 1468856059\r\n        },\r\n        {\r\n            \"created_at\": 1468856009,\r" +
            "\n            \"id\": \"867edb741cc045fa851068f96ca95a43936dd614\",\r\n            \"ide" +
            "ntity_id\": \"03a78e036afb076a6606c5195c1f9b42\",\r\n            \"name\": \"Time series" +
            " analysis 2\",\r\n            \"parameters\": {\r\n                \"end\": 1468856009,\r\n" +
            "                \"start\": 1467646409\r\n            },\r\n            \"status\": \"Comp" +
            "leted\",\r\n            \"subscription_id\": \"e9dde04774540ac119c2317a4d15a8b3a135093" +
            "7\",\r\n            \"type\": \"analysis\",\r\n            \"updated_at\": 1468856019\r\n    " +
            "    }\r\n    ]\r\n}")]
        public string GetAll {
            get {
                return ((string)(this["GetAll"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
            ""created_at"": 1468879258,
            ""id"": ""6763dd472cf7e5af9cf1752627f11710a5335953"",
            ""identity_id"": ""03a78e036afb076a6606c5195c1f9b42"",
            ""name"": ""Bens Test"",
            ""parameters"": {
                ""end"": 1468863265,
                ""start"": 1468776865
            },
            ""status"": ""Completed"",
            ""subscription_id"": ""e9dde04774540ac119c2317a4d15a8b3a1350937"",
            ""type"": ""analysis"",
            ""updated_at"": 1468879261
        }")]
        public string GetOne {
            get {
                return ((string)(this["GetOne"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
            ""created_at"": 1468879258,
            ""id"": ""6763dd472cf7e5af9cf1752627f11710a5335953"",
            ""identity_id"": ""03a78e036afb076a6606c5195c1f9b42"",
            ""name"": ""Bens Test"",
            ""parameters"": {
                ""end"": 1468863265,
                ""start"": 1468776865
            },
            ""status"": ""Completed"",
            ""subscription_id"": ""e9dde04774540ac119c2317a4d15a8b3a1350937"",
            ""type"": ""analysis"",
            ""updated_at"": 1468879261
        }")]
        public string Create {
            get {
                return ((string)(this["Create"]));
            }
        }
    }
}
